<?php

/**
 * Hero Section Template Part
 * Based on HeroSection.vue
 */

$video_poster = get_template_directory_uri() . '/assets/images/carousel/img1.webp';
$video_source = get_template_directory_uri() . '/assets/videos/video.mp4';
$logo_image = get_template_directory_uri() . '/assets/images/icononly_transparent_nobuffer.png';
?>

<section class="relative h-screen w-full flex flex-col items-center justify-center overflow-hidden">
    <video
        autoplay
        muted
        loop
        playsinline
        class="absolute inset-0 w-full h-full object-cover"
        poster="<?php echo esc_url($video_poster); ?>"
        onerror="this.style.display='none';">
        <source src="<?php echo esc_url($video_source); ?>" type="video/mp4" />
    </video>

    <div class="absolute inset-0 bg-gradient-to-b from-[#0f203d]/70 via-[#0f203d]/80 to-[#0f203d]/90"></div>
    <div class="absolute inset-0 bg-[radial-gradient(circle_at_center,_var(--tw-gradient-stops))] from-[#0f203d]/50 to-[#0f203d]/90"></div>

    <div class="absolute inset-0 overflow-hidden" id="particles-container">
        <!-- Particles will be generated by JavaScript -->
    </div>

    <div class="relative z-10 flex flex-col items-center text-center px-4 max-w-4xl mx-auto">
        <div class="mb-12">
            <div class="relative">
                <div class="absolute inset-0 bg-[#d4b478] blur-[60px] opacity-10 rounded-full animate-pulse"></div>
                <img
                    src="<?php echo esc_url($logo_image); ?>"
                    alt="Logo Mark"
                    class="w-32 h-32 md:w-40 md:h-40 object-contain relative z-10 animate-float-slow" />
            </div>
        </div>

        <h1 class="text-[#d4b478] text-2xl md:text-4xl font-medium tracking-[0.2em] uppercase mb-4 relative">
            <span class="absolute -left-8 top-1/2 -translate-y-1/2 w-6 h-px bg-[#d4b478]/40 hidden md:block"></span>
            True Influence Method™️ — Joanna Horton McPherson
            <span class="absolute -right-8 top-1/2 -translate-y-1/2 w-6 h-px bg-[#d4b478]/40 hidden md:block"></span>
        </h1>

        <p class="text-[#faf8f5] font-serif italic text-xl md:text-3xl mb-8 font-light relative inline-block">
            <span class="absolute -top-3 -left-4 text-[#d4b478]/20 text-5xl font-serif">"</span>
            Your Voice Is Your Leadership.
            <span class="absolute -bottom-3 -right-4 text-[#d4b478]/20 text-5xl font-serif">"</span>
        </p>

        <p class="text-[#faf8f5]/80 text-lg md:text-xl max-w-2xl mb-12 leading-relaxed">
            You've built something real. Now it's time to speak about it in
            a way that moves rooms, earns trust, and creates a legacy that
            outlasts the work itself.
        </p>

        <div class="flex flex-col sm:flex-row gap-4">
            <a href="<?php echo esc_url(home_url('/apply')); ?>" class="group px-8 py-4 bg-[#d4b478] hover:bg-[#e8a838] text-[#0f203d] font-semibold rounded-lg transition-all hover:shadow-lg hover:shadow-[#d4b478]/20 text-center relative overflow-hidden">
                <span class="relative z-10 flex items-center gap-2">
                    Apply to Work With Joanna
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="group-hover:translate-x-1 transition-transform">
                        <line x1="5" y1="12" x2="19" y2="12"></line>
                        <polyline points="12 5 19 12 12 19"></polyline>
                    </svg>
                </span>
            </a>
            <a href="<?php echo esc_url(home_url('/programs')); ?>" class="px-8 py-4 border-2 border-[#d4b478] text-[#d4b478] hover:bg-[#d4b478]/10 font-semibold rounded-lg transition-all text-center">
                Explore Programs →
            </a>
        </div>
    </div>

    <div class="absolute bottom-12 left-1/2 transform -translate-x-1/2">
        <div class="animate-bounce">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-[#d4b478] opacity-60">
                <path d="M7 13l5 5 5-5M7 6l5 5 5-5"></path>
            </svg>
        </div>
    </div>
</section>