<?php

/**
 * About Page ACF Field Group
 *
 * Registers ACF fields for the about page template.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_about_page',
        'title' => 'About Page',
        'fields' => [
            // Hero Section
            [
                'key' => 'field_about_hero_badge',
                'label' => 'Hero Badge Text',
                'name' => 'about_hero_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the hero heading.',
                'required' => 0,
                'default_value' => 'Leadership & Executive Coaching',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_hero_heading',
                'label' => 'Hero Heading',
                'name' => 'about_hero_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the hero section.',
                'required' => 0,
                'default_value' => 'She Trains Leaders to Speak. And Speakers to Lead.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_hero_description',
                'label' => 'Hero Description',
                'name' => 'about_hero_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the hero heading.',
                'required' => 0,
                'default_value' => 'Joanna Horton McPherson helps leaders find their authentic voice through the True Influence Method™ — building trust, emotional clarity, and real-world impact.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_hero_primary_cta_text',
                'label' => 'Hero Primary CTA Text',
                'name' => 'about_hero_primary_cta_text',
                'type' => 'text',
                'instructions' => 'The text for the primary call-to-action button.',
                'required' => 0,
                'default_value' => 'Book Joanna to Speak',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_hero_primary_cta_link',
                'label' => 'Hero Primary CTA Link',
                'name' => 'about_hero_primary_cta_link',
                'type' => 'page_link',
                'instructions' => 'Select the page for the primary call-to-action button.',
                'required' => 0,
                'post_type' => ['page'],
                'taxonomy' => [],
                'allow_null' => 0,
                'multiple' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_hero_secondary_cta_text',
                'label' => 'Hero Secondary CTA Text',
                'name' => 'about_hero_secondary_cta_text',
                'type' => 'text',
                'instructions' => 'The text for the secondary call-to-action button.',
                'required' => 0,
                'default_value' => 'Learn More',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_hero_secondary_cta_link',
                'label' => 'Hero Secondary CTA Link',
                'name' => 'about_hero_secondary_cta_link',
                'type' => 'text',
                'instructions' => 'The URL or anchor for the secondary call-to-action button (e.g., #about).',
                'required' => 0,
                'default_value' => '#about',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_hero_featured_on',
                'label' => 'Featured On Text',
                'name' => 'about_hero_featured_on',
                'type' => 'text',
                'instructions' => 'The text displayed showing where Joanna has been featured.',
                'required' => 0,
                'default_value' => 'As featured on MTV, Harvard, USA Today',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_hero_image',
                'label' => 'Hero Image',
                'name' => 'about_hero_image',
                'type' => 'image',
                'instructions' => 'The main hero image.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_hero_overlay_quote',
                'label' => 'Hero Overlay Quote',
                'name' => 'about_hero_overlay_quote',
                'type' => 'text',
                'instructions' => 'The quote text displayed in the overlay card.',
                'required' => 0,
                'default_value' => 'True Influence',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_hero_overlay_label',
                'label' => 'Hero Overlay Label',
                'name' => 'about_hero_overlay_label',
                'type' => 'text',
                'instructions' => 'The label text displayed below the overlay quote.',
                'required' => 0,
                'default_value' => 'Signature Method',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Story Section
            [
                'key' => 'field_about_story_badge',
                'label' => 'Story Badge Text',
                'name' => 'about_story_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the story heading.',
                'required' => 0,
                'default_value' => 'Her Story',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_story_heading',
                'label' => 'Story Heading',
                'name' => 'about_story_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the story section.',
                'required' => 0,
                'default_value' => 'It Started With a Question: What If the Most Powerful Thing You Could Do Is Tell the Truth?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_story_description_1',
                'label' => 'Story Description Paragraph 1',
                'name' => 'about_story_description_1',
                'type' => 'textarea',
                'instructions' => 'The first description paragraph for the story section.',
                'required' => 0,
                'default_value' => 'Joanna has spent a lifetime at the edges of transformation — in theatre, in classrooms, in boardrooms, in communities. As an actress, educator, entrepreneur, and investor, she learned that the leaders who create lasting impact are not the loudest or the most polished. They are the most honest.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_story_description_2',
                'label' => 'Story Description Paragraph 2',
                'name' => 'about_story_description_2',
                'type' => 'textarea',
                'instructions' => 'The second description paragraph for the story section.',
                'required' => 0,
                'default_value' => 'She created the True Influence Method™️ to give leaders a rigorous, human-centered process for doing exactly that. Through her signature interview-based approach, Joanna surfaces the truth beneath the noise — the defining moment, the real why, the lived experience that makes a message land.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_story_blockquote',
                'label' => 'Story Blockquote',
                'name' => 'about_story_blockquote',
                'type' => 'textarea',
                'instructions' => 'The blockquote text for the story section.',
                'required' => 0,
                'default_value' => 'The result is a voice that doesn\'t just communicate. It leads.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_story_image',
                'label' => 'Story Image',
                'name' => 'about_story_image',
                'type' => 'image',
                'instructions' => 'The main image for the story section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_story_quote_overlay',
                'label' => 'Story Quote Overlay',
                'name' => 'about_story_quote_overlay',
                'type' => 'textarea',
                'instructions' => 'The quote text displayed in the image overlay.',
                'required' => 0,
                'default_value' => 'The leaders who create lasting impact are not the loudest or the most polished. They are the most honest.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_story_stats_number',
                'label' => 'Story Stats Number',
                'name' => 'about_story_stats_number',
                'type' => 'text',
                'instructions' => 'The number displayed in the stats card.',
                'required' => 0,
                'default_value' => '30+',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_story_stats_label',
                'label' => 'Story Stats Label',
                'name' => 'about_story_stats_label',
                'type' => 'text',
                'instructions' => 'The label displayed below the number in the stats card.',
                'required' => 0,
                'default_value' => 'Years of Impact',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Credentials Section
            [
                'key' => 'field_about_credentials_badge',
                'label' => 'Credentials Badge Text',
                'name' => 'about_credentials_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the credentials heading.',
                'required' => 0,
                'default_value' => 'Background',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_credentials_heading',
                'label' => 'Credentials Heading',
                'name' => 'about_credentials_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the credentials section.',
                'required' => 0,
                'default_value' => 'A Lifetime of Excellence',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_credentials_items',
                'label' => 'Credentials',
                'name' => 'about_credentials_items',
                'type' => 'repeater',
                'instructions' => 'Add credential items (Harvard Graduate, 6x Founder, TEDx Speaker, etc.).',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Credential',
                'sub_fields' => [
                    [
                        'key' => 'field_about_credential_title',
                        'label' => 'Credential Title',
                        'name' => 'credential_title',
                        'type' => 'text',
                        'instructions' => 'The title for this credential.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Harvard Graduate',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_about_credential_subtitle',
                        'label' => 'Credential Subtitle',
                        'name' => 'credential_subtitle',
                        'type' => 'text',
                        'instructions' => 'The subtitle for this credential.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., World-class education',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Philosophy Section
            [
                'key' => 'field_about_philosophy_badge',
                'label' => 'Philosophy Badge Text',
                'name' => 'about_philosophy_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the philosophy heading.',
                'required' => 0,
                'default_value' => 'Philosophy',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_philosophy_heading',
                'label' => 'Philosophy Heading',
                'name' => 'about_philosophy_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the philosophy section.',
                'required' => 0,
                'default_value' => 'Your Story Is Not Just Where You\'ve Been. It\'s the Reason People Choose to Follow You.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_philosophy_description',
                'label' => 'Philosophy Description',
                'name' => 'about_philosophy_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the philosophy section.',
                'required' => 0,
                'default_value' => 'Joanna believes that authentic communication is not a skill to be learned — it\'s a truth to be uncovered. Her work begins not with what you want to say, but with who you are and what you\'ve lived. From that foundation, she helps leaders build a voice that is authoritative, emotionally resonant, and entirely their own.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_philosophy_blockquote',
                'label' => 'Philosophy Blockquote',
                'name' => 'about_philosophy_blockquote',
                'type' => 'textarea',
                'instructions' => 'The blockquote text for the philosophy section.',
                'required' => 0,
                'default_value' => 'Being a voice for your work is not just good for sales. It\'s good for the soul.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_philosophy_author',
                'label' => 'Philosophy Author',
                'name' => 'about_philosophy_author',
                'type' => 'text',
                'instructions' => 'The author attribution for the philosophy blockquote.',
                'required' => 0,
                'default_value' => '— Joanna Horton McPherson',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_philosophy_image',
                'label' => 'Philosophy Image',
                'name' => 'about_philosophy_image',
                'type' => 'image',
                'instructions' => 'The main image for the philosophy section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_philosophy_quote_overlay',
                'label' => 'Philosophy Quote Overlay',
                'name' => 'about_philosophy_quote_overlay',
                'type' => 'textarea',
                'instructions' => 'The quote text displayed in the image overlay.',
                'required' => 0,
                'default_value' => 'Your story is not just where you\'ve been. It\'s the reason people choose to follow you.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // CTA Section
            [
                'key' => 'field_about_cta_heading',
                'label' => 'CTA Heading',
                'name' => 'about_cta_heading',
                'type' => 'text',
                'instructions' => 'The heading text for the CTA section.',
                'required' => 0,
                'default_value' => 'Ready to Find Your Voice?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_cta_description',
                'label' => 'CTA Description',
                'name' => 'about_cta_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the CTA section.',
                'required' => 0,
                'default_value' => 'The first step is a conversation. Fill out Joanna\'s private client inquiry form and her team will be in touch to guide you toward the right path.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_cta_button_text',
                'label' => 'CTA Button Text',
                'name' => 'about_cta_button_text',
                'type' => 'text',
                'instructions' => 'The text for the CTA button.',
                'required' => 0,
                'default_value' => 'Apply to Work With Joanna',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_cta_button_link',
                'label' => 'CTA Button Link',
                'name' => 'about_cta_button_link',
                'type' => 'page_link',
                'instructions' => 'Select the page for the CTA button.',
                'required' => 0,
                'post_type' => ['page'],
                'taxonomy' => [],
                'allow_null' => 0,
                'multiple' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_about_cta_logo_image',
                'label' => 'CTA Logo Image',
                'name' => 'about_cta_logo_image',
                'type' => 'image',
                'instructions' => 'The logo image displayed in the CTA section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-about.php',
                ],
            ],
        ],
        'menu_order' => 10,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [],
        'active' => true,
        'description' => 'Configure the about page content.',
    ]);
}
