<?php

/**
 * Community Page ACF Field Group
 *
 * Registers ACF fields for the community page template.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_community_page',
        'title' => 'Community Page',
        'fields' => [
            // Hero Section
            [
                'key' => 'field_community_hero_badge',
                'label' => 'Hero Badge Text',
                'name' => 'community_hero_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the hero heading.',
                'required' => 0,
                'default_value' => 'The Community',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_community_hero_heading',
                'label' => 'Hero Heading',
                'name' => 'community_hero_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the hero section.',
                'required' => 0,
                'default_value' => 'You Don\'t Do This Work Alone.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_community_hero_description_1',
                'label' => 'Hero Description Paragraph 1',
                'name' => 'community_hero_description_1',
                'type' => 'textarea',
                'instructions' => 'The first description paragraph displayed below the hero heading.',
                'required' => 0,
                'default_value' => 'The True Influence Method™️ is not just a program. It\'s a growing community of leaders committed to brave, authentic communication — people who believe that their voice is their most powerful leadership tool, and are doing the work to prove it.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_community_hero_description_2',
                'label' => 'Hero Description Paragraph 2',
                'name' => 'community_hero_description_2',
                'type' => 'textarea',
                'instructions' => 'The second description paragraph displayed below the first description.',
                'required' => 0,
                'default_value' => 'When you work with Joanna, you step into that community.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Navigation Cards Section
            [
                'key' => 'field_community_navigation_cards',
                'label' => 'Navigation Cards',
                'name' => 'community_navigation_cards',
                'type' => 'repeater',
                'instructions' => 'Add navigation cards that link to different community sections.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Navigation Card',
                'sub_fields' => [
                    [
                        'key' => 'field_community_card_title',
                        'label' => 'Card Title',
                        'name' => 'card_title',
                        'type' => 'text',
                        'instructions' => 'The title for this navigation card.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., The Vault',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_community_card_description',
                        'label' => 'Card Description',
                        'name' => 'card_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this navigation card.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., An exclusive digital library of frameworks, tools, and resources for members.',
                        'maxlength' => '',
                        'rows' => 2,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_community_card_link',
                        'label' => 'Card Link',
                        'name' => 'card_link',
                        'type' => 'page_link',
                        'instructions' => 'Select the page or enter the URL for this navigation card.',
                        'required' => 0,
                        'post_type' => ['page'],
                        'taxonomy' => [],
                        'allow_null' => 0,
                        'multiple' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // CTA Section
            [
                'key' => 'field_community_cta_heading',
                'label' => 'CTA Section Heading',
                'name' => 'community_cta_heading',
                'type' => 'text',
                'instructions' => 'The heading text for the CTA section.',
                'required' => 0,
                'default_value' => 'Ready to Join a Community of Leaders Who Speak with Courage?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_community_cta_description',
                'label' => 'CTA Section Description',
                'name' => 'community_cta_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the CTA section.',
                'required' => 0,
                'default_value' => 'Take the first step toward finding your voice and leading with authentic influence.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_community_cta_button_text',
                'label' => 'CTA Button Text',
                'name' => 'community_cta_button_text',
                'type' => 'text',
                'instructions' => 'The text for the CTA button.',
                'required' => 0,
                'default_value' => 'Apply to Work With Joanna',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_community_cta_button_link',
                'label' => 'CTA Button Link',
                'name' => 'community_cta_button_link',
                'type' => 'page_link',
                'instructions' => 'Select the page for the CTA button.',
                'required' => 0,
                'post_type' => ['page'],
                'taxonomy' => [],
                'allow_null' => 0,
                'multiple' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-community.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [
            'the_content',
            'excerpt',
            'discussion',
            'comments',
            'revisions',
            'slug',
            'author',
            'format',
            'page_attributes',
            'featured_image',
            'categories',
            'tags',
            'send-trackbacks',
        ],
        'active' => true,
        'description' => 'Fields for the Community page template.',
    ]);
}
