<?php

/**
 * Corporate Page ACF Field Group
 *
 * Registers ACF fields for the corporate page template.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_corporate_page',
        'title' => 'Corporate Page',
        'fields' => [
            // ─── Hero Section ───
            [
                'key' => 'field_corporate_hero_badge',
                'label' => 'Hero Badge Text',
                'name' => 'corporate_hero_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the hero heading.',
                'required' => 0,
                'default_value' => 'The True Influence Method™',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_hero_heading',
                'label' => 'Hero Heading',
                'name' => 'corporate_hero_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the hero section.',
                'required' => 0,
                'default_value' => 'Lead From Depth, Not Performance',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_hero_description',
                'label' => 'Hero Description',
                'name' => 'corporate_hero_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the hero heading.',
                'required' => 0,
                'default_value' => 'To lead effectively is a deeply personal journey. The True Influence Method™ deploys advanced frameworks to embody your message and vision so you can be an example of your greater purpose.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_hero_cta_text',
                'label' => 'Hero CTA Text',
                'name' => 'corporate_hero_cta_text',
                'type' => 'text',
                'instructions' => 'The text for the hero call-to-action button.',
                'required' => 0,
                'default_value' => 'Explore the Method',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_hero_cta_link',
                'label' => 'Hero CTA Link',
                'name' => 'corporate_hero_cta_link',
                'type' => 'text',
                'instructions' => 'The URL or anchor for the hero call-to-action button.',
                'required' => 0,
                'default_value' => '#the-method',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_hero_image',
                'label' => 'Hero Background Image',
                'name' => 'corporate_hero_image',
                'type' => 'image',
                'instructions' => 'The background image for the hero section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],

            // ─── Philosophy Section ───
            [
                'key' => 'field_corporate_philosophy_badge',
                'label' => 'Philosophy Badge Text',
                'name' => 'corporate_philosophy_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the philosophy heading.',
                'required' => 0,
                'default_value' => 'The Approach',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_philosophy_heading',
                'label' => 'Philosophy Heading',
                'name' => 'corporate_philosophy_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the philosophy section.',
                'required' => 0,
                'default_value' => 'Transformation Begins at the Source',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_philosophy_paragraph_1',
                'label' => 'Philosophy Paragraph 1',
                'name' => 'corporate_philosophy_paragraph_1',
                'type' => 'textarea',
                'instructions' => 'The first paragraph of the philosophy section.',
                'required' => 0,
                'default_value' => 'Hi, I\'m Joanna Horton McPherson. I approach blocks to income, influence and impact at the source: in the inner realm of leadership. To lead effectively is a deeply personal journey.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_philosophy_paragraph_2',
                'label' => 'Philosophy Paragraph 2',
                'name' => 'corporate_philosophy_paragraph_2',
                'type' => 'textarea',
                'instructions' => 'The second paragraph of the philosophy section.',
                'required' => 0,
                'default_value' => 'To address issues at the root, I deploy advanced frameworks to embody your message and vision so you can be an example of your greater purpose rather than a performance of it.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_philosophy_image',
                'label' => 'Philosophy Section Image',
                'name' => 'corporate_philosophy_image',
                'type' => 'image',
                'instructions' => 'The image displayed in the philosophy section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],

            // ─── The Method Section ───
            [
                'key' => 'field_corporate_method_badge',
                'label' => 'Method Badge Text',
                'name' => 'corporate_method_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the method heading.',
                'required' => 0,
                'default_value' => 'The System',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_method_heading',
                'label' => 'Method Heading',
                'name' => 'corporate_method_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the method section.',
                'required' => 0,
                'default_value' => 'The True Influence Method™',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_method_description',
                'label' => 'Method Description',
                'name' => 'corporate_method_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the method section.',
                'required' => 0,
                'default_value' => 'An intricate system of research-backed practices that bring founders, CEOs, and executives through a journey phase by phase of gaining deeper insights, taking them from performing their worth to leading from depth.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_method_outcomes',
                'label' => 'Method Outcomes',
                'name' => 'corporate_method_outcomes',
                'type' => 'repeater',
                'instructions' => 'The three breakthrough outcomes clients achieve.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Outcome',
                'sub_fields' => [
                    [
                        'key' => 'field_corporate_method_outcome_icon',
                        'label' => 'Outcome Icon',
                        'name' => 'outcome_icon',
                        'type' => 'select',
                        'instructions' => 'Select the icon for this outcome.',
                        'required' => 0,
                        'choices' => [
                            'Shield' => 'Shield (Inner trust)',
                            'Target' => 'Target (Clarity)',
                            'Crown' => 'Crown (Legacy)',
                            'Zap' => 'Zap (Breakthrough)',
                            'Compass' => 'Compass (Direction)',
                            'Eye' => 'Eye (Insight)',
                        ],
                        'default_value' => 'Shield',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_method_outcome_title',
                        'label' => 'Outcome Title',
                        'name' => 'outcome_title',
                        'type' => 'text',
                        'instructions' => 'The title for this outcome.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Overcome Self-Doubt',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '75',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_method_outcome_description',
                        'label' => 'Outcome Description',
                        'name' => 'outcome_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this outcome.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 2,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],

            // ─── Key Deliverables Section ───
            [
                'key' => 'field_corporate_deliverables_badge',
                'label' => 'Deliverables Badge Text',
                'name' => 'corporate_deliverables_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the deliverables heading.',
                'required' => 0,
                'default_value' => 'Key Deliverables',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_deliverables_heading',
                'label' => 'Deliverables Heading',
                'name' => 'corporate_deliverables_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the deliverables section.',
                'required' => 0,
                'default_value' => 'What You Will Achieve',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_deliverables_description',
                'label' => 'Deliverables Description',
                'name' => 'corporate_deliverables_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the deliverables section.',
                'required' => 0,
                'default_value' => 'The system goes beyond traditional learning to create breakthrough insights where clients can finally address issues at the root.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_deliverables_items',
                'label' => 'Deliverable Items',
                'name' => 'corporate_deliverables_items',
                'type' => 'repeater',
                'instructions' => 'Add deliverable items that describe what clients achieve.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Deliverable',
                'sub_fields' => [
                    [
                        'key' => 'field_corporate_deliverable_icon',
                        'label' => 'Deliverable Icon',
                        'name' => 'deliverable_icon',
                        'type' => 'select',
                        'instructions' => 'Select the icon for this deliverable.',
                        'required' => 0,
                        'choices' => [
                            'Target' => 'Target (Differentiator)',
                            'Mic' => 'Mic (Signature Message)',
                            'Award' => 'Award (Distinction)',
                            'Shield' => 'Shield (Trust & Safety)',
                            'Users' => 'Users (Team Safety)',
                            'TrendingUp' => 'TrendingUp (Profit Growth)',
                            'BookOpen' => 'BookOpen (Story)',
                            'Zap' => 'Zap (Breakthrough)',
                            'Crown' => 'Crown (Legacy)',
                        ],
                        'default_value' => 'Target',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_deliverable_title',
                        'label' => 'Deliverable Title',
                        'name' => 'deliverable_title',
                        'type' => 'text',
                        'instructions' => 'The title for this deliverable.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Discover Your Unique Key Differentiator',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '75',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_deliverable_description',
                        'label' => 'Deliverable Description',
                        'name' => 'deliverable_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this deliverable.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 2,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],

            // ─── Training Formats Section ───
            [
                'key' => 'field_corporate_formats_badge',
                'label' => 'Formats Badge Text',
                'name' => 'corporate_formats_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the training formats heading.',
                'required' => 0,
                'default_value' => 'How You Train',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_formats_heading',
                'label' => 'Formats Heading',
                'name' => 'corporate_formats_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the training formats section.',
                'required' => 0,
                'default_value' => 'Choose Your Transformation Setting',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_formats_description',
                'label' => 'Formats Description',
                'name' => 'corporate_formats_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the training formats section.',
                'required' => 0,
                'default_value' => 'Whether training as an exclusive private client, as a corporate team, or in a peer mastermind/retreat setting, the transformation begins with clarity and insight, causing growth not by increments but through shifts in trajectory.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_formats_items',
                'label' => 'Training Format Items',
                'name' => 'corporate_formats_items',
                'type' => 'repeater',
                'instructions' => 'Add training format options.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Format',
                'sub_fields' => [
                    [
                        'key' => 'field_corporate_format_icon',
                        'label' => 'Format Icon',
                        'name' => 'format_icon',
                        'type' => 'select',
                        'instructions' => 'Select the icon for this format.',
                        'required' => 0,
                        'choices' => [
                            'Crown' => 'Crown (Private Client)',
                            'Users' => 'Users (Corporate Team)',
                            'Award' => 'Award (Mastermind/Retreat)',
                            'Target' => 'Target (Focus)',
                            'Zap' => 'Zap (Intensive)',
                        ],
                        'default_value' => 'Crown',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_format_title',
                        'label' => 'Format Title',
                        'name' => 'format_title',
                        'type' => 'text',
                        'instructions' => 'The title for this training format.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Exclusive Private Client',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '75',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_format_description',
                        'label' => 'Format Description',
                        'name' => 'format_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this training format.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 2,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_format_image',
                        'label' => 'Format Image',
                        'name' => 'format_image',
                        'type' => 'image',
                        'instructions' => 'The image for this training format.',
                        'required' => 0,
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_format_popular',
                        'label' => 'Popular Format',
                        'name' => 'format_popular',
                        'type' => 'true_false',
                        'instructions' => 'Mark this format as featured/highlighted.',
                        'required' => 0,
                        'default_value' => 0,
                        'message' => 'Mark as featured',
                        'ui' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],

            // ─── Impact Section ───
            [
                'key' => 'field_corporate_impact_badge',
                'label' => 'Impact Badge Text',
                'name' => 'corporate_impact_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the impact heading.',
                'required' => 0,
                'default_value' => 'The Impact',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_impact_heading',
                'label' => 'Impact Heading',
                'name' => 'corporate_impact_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the impact section.',
                'required' => 0,
                'default_value' => 'From Truth to Scale',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_impact_quote',
                'label' => 'Impact Quote',
                'name' => 'corporate_impact_quote',
                'type' => 'textarea',
                'instructions' => 'The powerful quote displayed in the impact section.',
                'required' => 0,
                'default_value' => 'Leading from the stage is not about performance; it is about truth.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_impact_description',
                'label' => 'Impact Description',
                'name' => 'corporate_impact_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the impact section, describing how truth expands outward.',
                'required' => 0,
                'default_value' => 'These perspective shifts engage your authentic voice, turning lived experience into sophisticated and unique messages that shape your industry, shift culture, and open new paths of income and impact.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_impact_stat_value',
                'label' => 'Impact Stat Value',
                'name' => 'corporate_impact_stat_value',
                'type' => 'text',
                'instructions' => 'The key statistic value (e.g., 40%+).',
                'required' => 0,
                'default_value' => '40%+',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_impact_stat_label',
                'label' => 'Impact Stat Label',
                'name' => 'corporate_impact_stat_label',
                'type' => 'text',
                'instructions' => 'The label describing the statistic.',
                'required' => 0,
                'default_value' => 'Organizational Profit Increase',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_impact_image',
                'label' => 'Impact Section Image',
                'name' => 'corporate_impact_image',
                'type' => 'image',
                'instructions' => 'The image displayed in the impact section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_impact_stats',
                'label' => 'Impact Statistics',
                'name' => 'corporate_impact_stats',
                'type' => 'repeater',
                'instructions' => 'Add key impact statistics to display in the stats row.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 6,
                'layout' => 'block',
                'button_label' => 'Add Stat',
                'sub_fields' => [
                    [
                        'key' => 'field_corporate_impact_stat_item_icon',
                        'label' => 'Stat Icon',
                        'name' => 'stat_icon',
                        'type' => 'select',
                        'instructions' => 'Select the icon for this statistic.',
                        'required' => 0,
                        'choices' => [
                            'TrendingUp' => 'TrendingUp (Growth)',
                            'Users' => 'Users (People)',
                            'Target' => 'Target (Focus)',
                            'Award' => 'Award (Achievement)',
                            'Crown' => 'Crown (Leadership)',
                            'Zap' => 'Zap (Energy)',
                            'Shield' => 'Shield (Protection)',
                            'Compass' => 'Compass (Direction)',
                        ],
                        'default_value' => 'TrendingUp',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_impact_stat_item_value',
                        'label' => 'Stat Value',
                        'name' => 'stat_value',
                        'type' => 'text',
                        'instructions' => 'The statistic value (e.g., 40%+, 12+, 3).',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., 40%+',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '30',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_impact_stat_item_label',
                        'label' => 'Stat Label',
                        'name' => 'stat_label',
                        'type' => 'text',
                        'instructions' => 'The label describing the statistic.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Profit Growth',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],

            // ─── CTA Section ───
            [
                'key' => 'field_corporate_cta_heading',
                'label' => 'CTA Section Heading',
                'name' => 'corporate_cta_heading',
                'type' => 'text',
                'instructions' => 'The heading text for the final CTA section.',
                'required' => 0,
                'default_value' => 'Begin Your Transformation',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_cta_description',
                'label' => 'CTA Section Description',
                'name' => 'corporate_cta_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the final CTA section.',
                'required' => 0,
                'default_value' => 'The transformation begins with clarity and insight. Whether as a private client, corporate team, or in a retreat setting—growth comes not by increments but through shifts in trajectory.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_cta_button_text',
                'label' => 'CTA Button Text',
                'name' => 'corporate_cta_button_text',
                'type' => 'text',
                'instructions' => 'The text for the final CTA button.',
                'required' => 0,
                'default_value' => 'Schedule a Consultation',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_cta_button_link',
                'label' => 'CTA Button Link',
                'name' => 'corporate_cta_button_link',
                'type' => 'page_link',
                'instructions' => 'Select the page for the final CTA button.',
                'required' => 0,
                'post_type' => ['page'],
                'taxonomy' => [],
                'allow_null' => 0,
                'multiple' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-corporate.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [
            'the_content',
            'excerpt',
            'discussion',
            'comments',
            'revisions',
            'slug',
            'author',
            'format',
            'page_attributes',
            'featured_image',
            'categories',
            'tags',
            'send-trackbacks',
        ],
        'active' => true,
        'description' => 'Fields for the Corporate page template.',
    ]);
}
