<?php

/**
 * Corporate Page ACF Field Group
 *
 * Registers ACF fields for the corporate page template.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_corporate_page',
        'title' => 'Corporate Page',
        'fields' => [
            // Hero Section
            [
                'key' => 'field_corporate_hero_badge',
                'label' => 'Hero Badge Text',
                'name' => 'corporate_hero_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the hero heading.',
                'required' => 0,
                'default_value' => 'For Organizations',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_hero_heading',
                'label' => 'Hero Heading',
                'name' => 'corporate_hero_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the hero section.',
                'required' => 0,
                'default_value' => 'Transform Presentations Into Revenue',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_hero_description',
                'label' => 'Hero Description',
                'name' => 'corporate_hero_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the hero heading.',
                'required' => 0,
                'default_value' => 'The True Influence Method™ aligns leadership voice, message clarity, and audience psychology for measurable business outcomes.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_hero_cta_text',
                'label' => 'Hero CTA Text',
                'name' => 'corporate_hero_cta_text',
                'type' => 'text',
                'instructions' => 'The text for the hero call-to-action button.',
                'required' => 0,
                'default_value' => 'Explore Services',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_hero_cta_link',
                'label' => 'Hero CTA Link',
                'name' => 'corporate_hero_cta_link',
                'type' => 'text',
                'instructions' => 'The URL or anchor for the hero call-to-action button (e.g., #services).',
                'required' => 0,
                'default_value' => '#services',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_hero_image',
                'label' => 'Hero Background Image',
                'name' => 'corporate_hero_image',
                'type' => 'image',
                'instructions' => 'The background image for the hero section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Problem Section
            [
                'key' => 'field_corporate_problem_badge',
                'label' => 'Problem Badge Text',
                'name' => 'corporate_problem_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the problem heading.',
                'required' => 0,
                'default_value' => 'The Challenge',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_problem_heading',
                'label' => 'Problem Heading',
                'name' => 'corporate_problem_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the problem section.',
                'required' => 0,
                'default_value' => 'Presentations That Inform But Don\'t Convert',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_problem_items',
                'label' => 'Problem Items',
                'name' => 'corporate_problem_items',
                'type' => 'repeater',
                'instructions' => 'Add problem items that describe common presentation challenges.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Problem Item',
                'sub_fields' => [
                    [
                        'key' => 'field_corporate_problem_item_text',
                        'label' => 'Problem Text',
                        'name' => 'problem_item_text',
                        'type' => 'text',
                        'instructions' => 'The text for this problem item.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Audiences don\'t see their problem',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_problem_image',
                'label' => 'Problem Section Image',
                'name' => 'corporate_problem_image',
                'type' => 'image',
                'instructions' => 'The image displayed in the problem section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Solution Section
            [
                'key' => 'field_corporate_solution_badge',
                'label' => 'Solution Badge Text',
                'name' => 'corporate_solution_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the solution heading.',
                'required' => 0,
                'default_value' => 'The Solution',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_solution_heading',
                'label' => 'Solution Heading',
                'name' => 'corporate_solution_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the solution section.',
                'required' => 0,
                'default_value' => 'True Influence Method™',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_solution_description',
                'label' => 'Solution Description',
                'name' => 'corporate_solution_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the solution heading.',
                'required' => 0,
                'default_value' => 'Every presentation drives measurable business outcomes',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_solution_items',
                'label' => 'Solution Items',
                'name' => 'corporate_solution_items',
                'type' => 'repeater',
                'instructions' => 'Add solution items that describe the True Influence Method outcomes.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Solution Item',
                'sub_fields' => [
                    [
                        'key' => 'field_corporate_solution_item_image',
                        'label' => 'Solution Image',
                        'name' => 'solution_item_image',
                        'type' => 'image',
                        'instructions' => 'The image for this solution item.',
                        'required' => 0,
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_solution_item_title',
                        'label' => 'Solution Title',
                        'name' => 'solution_item_title',
                        'type' => 'text',
                        'instructions' => 'The title for this solution item.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Audience Sees Their Problem',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Services Section
            [
                'key' => 'field_corporate_services_badge',
                'label' => 'Services Badge Text',
                'name' => 'corporate_services_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the services heading.',
                'required' => 0,
                'default_value' => 'Services',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_services_heading',
                'label' => 'Services Heading',
                'name' => 'corporate_services_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the services section.',
                'required' => 0,
                'default_value' => 'Three Levels of Transformation',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_services',
                'label' => 'Services',
                'name' => 'corporate_services',
                'type' => 'repeater',
                'instructions' => 'Add service levels with details.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Service',
                'sub_fields' => [
                    [
                        'key' => 'field_corporate_service_level',
                        'label' => 'Service Level',
                        'name' => 'service_level',
                        'type' => 'text',
                        'instructions' => 'The level designation for this service (e.g., Level 1).',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Level 1',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_service_name',
                        'label' => 'Service Name',
                        'name' => 'service_name',
                        'type' => 'text',
                        'instructions' => 'The name of this service.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Signature Talk',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_service_description',
                        'label' => 'Service Description',
                        'name' => 'service_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this service.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Increase sales through message alignment',
                        'maxlength' => '',
                        'rows' => 2,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_service_image',
                        'label' => 'Service Image',
                        'name' => 'service_image',
                        'type' => 'image',
                        'instructions' => 'The image for this service.',
                        'required' => 0,
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_service_icon',
                        'label' => 'Service Icon',
                        'name' => 'service_icon',
                        'type' => 'select',
                        'instructions' => 'Select the icon for this service.',
                        'required' => 0,
                        'choices' => [
                            'Target' => 'Target (Circle with rings)',
                            'Award' => 'Award (Medal)',
                            'Crown' => 'Crown (Star)',
                        ],
                        'default_value' => 'Target',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_service_features',
                        'label' => 'Service Features',
                        'name' => 'service_features',
                        'type' => 'repeater',
                        'instructions' => 'Add features included in this service.',
                        'required' => 0,
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => 'Add Feature',
                        'sub_fields' => [
                            [
                                'key' => 'field_corporate_service_feature',
                                'label' => 'Feature',
                                'name' => 'service_feature',
                                'type' => 'text',
                                'instructions' => 'The feature text.',
                                'required' => 0,
                                'default_value' => '',
                                'placeholder' => 'e.g., Target audience identification',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_service_price',
                        'label' => 'Service Price',
                        'name' => 'service_price',
                        'type' => 'text',
                        'instructions' => 'The price for this service.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., $35,000',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_service_popular',
                        'label' => 'Popular Service',
                        'name' => 'service_popular',
                        'type' => 'true_false',
                        'instructions' => 'Mark this service as popular (shows a "Popular" badge).',
                        'required' => 0,
                        'default_value' => 0,
                        'message' => 'Mark as popular',
                        'ui' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Results Section
            [
                'key' => 'field_corporate_results_badge',
                'label' => 'Results Badge Text',
                'name' => 'corporate_results_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the results heading.',
                'required' => 0,
                'default_value' => 'Results',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_results_heading',
                'label' => 'Results Heading',
                'name' => 'corporate_results_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the results section.',
                'required' => 0,
                'default_value' => 'Tangible Outcomes',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_results_items',
                'label' => 'Results Items',
                'name' => 'corporate_results_items',
                'type' => 'repeater',
                'instructions' => 'Add result statistics with value and label.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Result',
                'sub_fields' => [
                    [
                        'key' => 'field_corporate_result_value',
                        'label' => 'Result Value',
                        'name' => 'result_value',
                        'type' => 'text',
                        'instructions' => 'The value/statistic to display.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., 40%+',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_corporate_result_label',
                        'label' => 'Result Label',
                        'name' => 'result_label',
                        'type' => 'text',
                        'instructions' => 'The label describing the result.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Sales Activity Increase',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_results_quote',
                'label' => 'Results Quote',
                'name' => 'corporate_results_quote',
                'type' => 'textarea',
                'instructions' => 'The quote text displayed in the results section.',
                'required' => 0,
                'default_value' => 'This is not presentation coaching. This is revenue-aligned communication strategy.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_results_attribution',
                'label' => 'Results Quote Attribution',
                'name' => 'corporate_results_attribution',
                'type' => 'text',
                'instructions' => 'The attribution for the quote.',
                'required' => 0,
                'default_value' => 'True Influence Method™',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_results_image',
                'label' => 'Results Section Image',
                'name' => 'corporate_results_image',
                'type' => 'image',
                'instructions' => 'The image displayed in the results section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Investment Section
            [
                'key' => 'field_corporate_investment_badge',
                'label' => 'Investment Badge Text',
                'name' => 'corporate_investment_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the investment heading.',
                'required' => 0,
                'default_value' => 'Investment',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_investment_heading',
                'label' => 'Investment Heading',
                'name' => 'corporate_investment_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the investment section.',
                'required' => 0,
                'default_value' => 'Choose Your Level',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_investment_cta_text',
                'label' => 'Investment CTA Text',
                'name' => 'corporate_investment_cta_text',
                'type' => 'text',
                'instructions' => 'The text for the investment call-to-action button.',
                'required' => 0,
                'default_value' => 'Get Started',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_investment_cta_link',
                'label' => 'Investment CTA Link',
                'name' => 'corporate_investment_cta_link',
                'type' => 'page_link',
                'instructions' => 'Select the page for the investment call-to-action button.',
                'required' => 0,
                'post_type' => ['page'],
                'taxonomy' => [],
                'allow_null' => 0,
                'multiple' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // CTA Section
            [
                'key' => 'field_corporate_cta_heading',
                'label' => 'CTA Section Heading',
                'name' => 'corporate_cta_heading',
                'type' => 'text',
                'instructions' => 'The heading text for the final CTA section.',
                'required' => 0,
                'default_value' => 'Ready to Transform?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_cta_description',
                'label' => 'CTA Section Description',
                'name' => 'corporate_cta_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the final CTA section.',
                'required' => 0,
                'default_value' => 'Let\'s discuss how the True Influence Method™ can help you achieve measurable business outcomes.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_cta_button_text',
                'label' => 'CTA Button Text',
                'name' => 'corporate_cta_button_text',
                'type' => 'text',
                'instructions' => 'The text for the final CTA button.',
                'required' => 0,
                'default_value' => 'Schedule a Consultation',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_corporate_cta_button_link',
                'label' => 'CTA Button Link',
                'name' => 'corporate_cta_button_link',
                'type' => 'page_link',
                'instructions' => 'Select the page for the final CTA button.',
                'required' => 0,
                'post_type' => ['page'],
                'taxonomy' => [],
                'allow_null' => 0,
                'multiple' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-corporate.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [
            'the_content',
            'excerpt',
            'discussion',
            'comments',
            'revisions',
            'slug',
            'author',
            'format',
            'page_attributes',
            'featured_image',
            'categories',
            'tags',
            'send-trackbacks',
        ],
        'active' => true,
        'description' => 'Fields for the Corporate page template.',
    ]);
}
