<?php

/**
 * Events Page ACF Field Group
 *
 * Registers ACF fields for the events page template.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_events_page',
        'title' => 'Events Page',
        'fields' => [
            // Hero Section
            [
                'key' => 'field_events_hero_badge',
                'label' => 'Hero Badge Text',
                'name' => 'events_hero_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the hero heading.',
                'required' => 0,
                'default_value' => 'Quarterly Experiences',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_events_hero_heading',
                'label' => 'Hero Heading',
                'name' => 'events_hero_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the hero section.',
                'required' => 0,
                'default_value' => 'Quarterly Retreats & Events',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_events_hero_description_1',
                'label' => 'Hero Description (Paragraph 1)',
                'name' => 'events_hero_description_1',
                'type' => 'textarea',
                'instructions' => 'The first description paragraph displayed below the hero heading.',
                'required' => 0,
                'default_value' => 'Private clients and Mastermind members join Joanna for quarterly retreat experiences — intimate, immersive days designed to deepen clarity, accelerate momentum, and reconnect with the community of leaders doing this work.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_events_hero_description_2',
                'label' => 'Hero Description (Paragraph 2)',
                'name' => 'events_hero_description_2',
                'type' => 'textarea',
                'instructions' => 'The second description paragraph displayed below the hero heading.',
                'required' => 0,
                'default_value' => 'These are not conferences. They are transformational rooms — places where real work happens and real connections are made.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Past Events Section
            [
                'key' => 'field_events_past_badge',
                'label' => 'Past Events Badge Text',
                'name' => 'events_past_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the past events heading.',
                'required' => 0,
                'default_value' => 'Past Events',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_events_past_heading',
                'label' => 'Past Events Heading',
                'name' => 'events_past_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the past events section.',
                'required' => 0,
                'default_value' => 'Transformational Experiences',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_events_past_description',
                'label' => 'Past Events Description',
                'name' => 'events_past_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the past events heading.',
                'required' => 0,
                'default_value' => 'Discover the kinds of events our community has experienced together.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_events_past_events',
                'label' => 'Past Events',
                'name' => 'events_past_events',
                'type' => 'repeater',
                'instructions' => 'Add past events to display in the events section.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Event',
                'sub_fields' => [
                    [
                        'key' => 'field_events_past_event_type',
                        'label' => 'Event Type',
                        'name' => 'event_type',
                        'type' => 'text',
                        'instructions' => 'The type/category of this event (e.g., Speaker Training, Leadership Intensive).',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Speaker Training',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_events_past_event_title',
                        'label' => 'Event Title',
                        'name' => 'event_title',
                        'type' => 'text',
                        'instructions' => 'The title of this event.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Speak & Rise Speaker Training',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_events_past_event_description',
                        'label' => 'Event Description',
                        'name' => 'event_description',
                        'type' => 'textarea',
                        'instructions' => 'The description of this event.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., An intensive workshop focused on developing authentic presence and delivering your message with impact.',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_events_past_event_icon',
                        'label' => 'Event Icon (SVG)',
                        'name' => 'event_icon',
                        'type' => 'textarea',
                        'instructions' => 'Paste the SVG code for the event icon. Use the full SVG tag including xmlns attribute.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#d4b478" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" /></svg>',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // What to Expect Section
            [
                'key' => 'field_events_expect_badge',
                'label' => 'What to Expect Badge Text',
                'name' => 'events_expect_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the what to expect heading.',
                'required' => 0,
                'default_value' => 'What to Expect',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_events_expect_heading',
                'label' => 'What to Expect Heading',
                'name' => 'events_expect_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the what to expect section.',
                'required' => 0,
                'default_value' => 'More Than Just Events',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_events_expect_description',
                'label' => 'What to Expect Description',
                'name' => 'events_expect_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the what to expect heading.',
                'required' => 0,
                'default_value' => 'Our retreats and events are carefully designed experiences that create lasting transformation.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_events_expect_features',
                'label' => 'What to Expect Features',
                'name' => 'events_expect_features',
                'type' => 'repeater',
                'instructions' => 'Add features that describe what attendees can expect from the events.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Feature',
                'sub_fields' => [
                    [
                        'key' => 'field_events_expect_feature_title',
                        'label' => 'Feature Title',
                        'name' => 'feature_title',
                        'type' => 'text',
                        'instructions' => 'The title of this feature.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Deep Connection',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_events_expect_feature_description',
                        'label' => 'Feature Description',
                        'name' => 'feature_description',
                        'type' => 'textarea',
                        'instructions' => 'The description of this feature.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Build meaningful relationships with other leaders committed to authentic communication.',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // CTA Section
            [
                'key' => 'field_events_cta_heading',
                'label' => 'CTA Heading',
                'name' => 'events_cta_heading',
                'type' => 'text',
                'instructions' => 'The heading text for the CTA section.',
                'required' => 0,
                'default_value' => 'Ready to Join Our Next Retreat?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_events_cta_description',
                'label' => 'CTA Description',
                'name' => 'events_cta_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the CTA heading.',
                'required' => 0,
                'default_value' => 'Private clients and Mastermind members receive exclusive access to our quarterly retreat experiences. Apply today to begin your journey.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_events_cta_primary_text',
                'label' => 'Primary CTA Button Text',
                'name' => 'events_cta_primary_text',
                'type' => 'text',
                'instructions' => 'The text for the primary call-to-action button.',
                'required' => 0,
                'default_value' => 'Apply to Work With Joanna',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_events_cta_primary_link',
                'label' => 'Primary CTA Button Link',
                'name' => 'events_cta_primary_link',
                'type' => 'page_link',
                'instructions' => 'Select the page for the primary call-to-action button.',
                'required' => 0,
                'post_type' => ['page'],
                'taxonomy' => [],
                'allow_null' => 0,
                'multiple' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_events_cta_secondary_text',
                'label' => 'Secondary CTA Button Text',
                'name' => 'events_cta_secondary_text',
                'type' => 'text',
                'instructions' => 'The text for the secondary call-to-action button.',
                'required' => 0,
                'default_value' => 'Explore Programs',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_events_cta_secondary_link',
                'label' => 'Secondary CTA Button Link',
                'name' => 'events_cta_secondary_link',
                'type' => 'page_link',
                'instructions' => 'Select the page for the secondary call-to-action button.',
                'required' => 0,
                'post_type' => ['page'],
                'taxonomy' => [],
                'allow_null' => 0,
                'multiple' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-events.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [
            'the_content',
            'excerpt',
            'discussion',
            'comments',
            'revisions',
            'slug',
            'author',
            'format',
            'page_attributes',
            'featured_image',
            'categories',
            'tags',
            'send-trackbacks',
        ],
        'active' => true,
        'description' => 'ACF fields for the Events page template.',
    ]);
}
