<?php

/**
 * Intro Section ACF Field Group
 *
 * Registers ACF fields for the intro section on the front page.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_intro_section',
        'title' => 'Intro Section',
        'fields' => [
            [
                'key' => 'field_intro_badge_text',
                'label' => 'Badge Text',
                'name' => 'intro_badge_text',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the heading.',
                'required' => 0,
                'default_value' => 'The Work',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_intro_heading',
                'label' => 'Section Heading',
                'name' => 'intro_heading',
                'type' => 'text',
                'instructions' => 'The main heading for the intro section.',
                'required' => 0,
                'default_value' => "You Don't Need a Better Script. You Need Your True Story.",
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_intro_description_1',
                'label' => 'Description Paragraph 1',
                'name' => 'intro_description_1',
                'type' => 'textarea',
                'instructions' => 'The first description paragraph.',
                'required' => 0,
                'default_value' => "Most leaders know what they do. Very few can say it in a way that makes people lean in, trust them, and follow. That gap — between your impact and your ability to articulate it — is exactly where Joanna works.",
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_intro_description_2',
                'label' => 'Description Paragraph 2',
                'name' => 'intro_description_2',
                'type' => 'textarea',
                'instructions' => 'The second description paragraph.',
                'required' => 0,
                'default_value' => "The True Influence Method™️ is not speaking coaching. It's a deep, structured process that surfaces the truth behind your work, shapes it into a message that is unmistakably yours, and trains you to deliver it with the kind of authority and openness that changes rooms.",
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_intro_main_image',
                'label' => 'Main Image',
                'name' => 'intro_main_image',
                'type' => 'image',
                'instructions' => 'The main image displayed on the right side of the section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_intro_stats_number',
                'label' => 'Stats Card Number',
                'name' => 'intro_stats_number',
                'type' => 'text',
                'instructions' => 'The number displayed in the stats card.',
                'required' => 0,
                'default_value' => '100+',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_intro_stats_label',
                'label' => 'Stats Card Label',
                'name' => 'intro_stats_label',
                'type' => 'text',
                'instructions' => 'The label displayed below the number in the stats card.',
                'required' => 0,
                'default_value' => 'Leaders Transformed',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_intro_features',
                'label' => 'Features',
                'name' => 'intro_features',
                'type' => 'repeater',
                'instructions' => 'Add feature items (Personal, Proven, Transformative).',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 3,
                'layout' => 'block',
                'button_label' => 'Add Feature',
                'sub_fields' => [
                    [
                        'key' => 'field_intro_feature_image',
                        'label' => 'Feature Image',
                        'name' => 'feature_image',
                        'type' => 'image',
                        'instructions' => 'The image for this feature.',
                        'required' => 0,
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_intro_feature_title',
                        'label' => 'Feature Title',
                        'name' => 'feature_title',
                        'type' => 'text',
                        'instructions' => 'The title for this feature.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Personal',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_intro_feature_subtitle',
                        'label' => 'Feature Subtitle',
                        'name' => 'feature_subtitle',
                        'type' => 'text',
                        'instructions' => 'The subtitle for this feature.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., 1-on-1 Focus',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'front-page.php',
                ],
            ],
        ],
        'menu_order' => 1,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [],
        'active' => true,
        'description' => 'Configure the intro section content for the front page.',
    ]);
}
