<?php

/**
 * Journey Page ACF Field Group
 *
 * Registers ACF fields for the journey page template.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_journey_page',
        'title' => 'Journey Page',
        'fields' => [
            // Hero Section
            [
                'key' => 'field_journey_hero_badge',
                'label' => 'Hero Badge Text',
                'name' => 'journey_hero_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the hero heading.',
                'required' => 0,
                'default_value' => 'The Process',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_hero_heading',
                'label' => 'Hero Heading',
                'name' => 'journey_hero_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the hero section (first part).',
                'required' => 0,
                'default_value' => 'A Process Rooted in Truth.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_hero_heading_alt',
                'label' => 'Hero Heading Alt (Highlighted)',
                'name' => 'journey_hero_heading_alt',
                'type' => 'text',
                'instructions' => 'The highlighted second part of the hero heading.',
                'required' => 0,
                'default_value' => 'Built Around You.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_hero_description',
                'label' => 'Hero Description',
                'name' => 'journey_hero_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the hero heading.',
                'required' => 0,
                'default_value' => 'The True Influence Method™️ is not a framework you slot yourself into. It\'s a living process — responsive, deep, and entirely grounded in who you are. It moves through five phases, each building on the last, until your message and your delivery are one.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_hero_image',
                'label' => 'Hero Image',
                'name' => 'journey_hero_image',
                'type' => 'image',
                'instructions' => 'The main hero image.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // 5 Phases Section
            [
                'key' => 'field_journey_phases_badge',
                'label' => 'Phases Badge Text',
                'name' => 'journey_phases_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the phases heading.',
                'required' => 0,
                'default_value' => 'The 5-Phase Journey',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_phases_heading',
                'label' => 'Phases Heading',
                'name' => 'journey_phases_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the phases section (first part).',
                'required' => 0,
                'default_value' => 'From Discovering Your Story',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_phases_heading_alt',
                'label' => 'Phases Heading Alt (Highlighted)',
                'name' => 'journey_phases_heading_alt',
                'type' => 'text',
                'instructions' => 'The highlighted second part of the phases heading.',
                'required' => 0,
                'default_value' => 'to Leading With It.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_phases',
                'label' => 'Phases',
                'name' => 'journey_phases',
                'type' => 'repeater',
                'instructions' => 'Add the five phases of the journey.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Phase',
                'sub_fields' => [
                    [
                        'key' => 'field_journey_phase_number',
                        'label' => 'Phase Number',
                        'name' => 'phase_number',
                        'type' => 'text',
                        'instructions' => 'The phase number (e.g., Phase One).',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Phase One',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_journey_phase_title',
                        'label' => 'Phase Title',
                        'name' => 'phase_title',
                        'type' => 'text',
                        'instructions' => 'The title for this phase.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Discover',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_journey_phase_subtitle',
                        'label' => 'Phase Subtitle',
                        'name' => 'phase_subtitle',
                        'type' => 'text',
                        'instructions' => 'The subtitle for this phase.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., The Defining Moment',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_journey_phase_description',
                        'label' => 'Phase Description',
                        'name' => 'phase_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this phase.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_journey_phase_image',
                        'label' => 'Phase Image',
                        'name' => 'phase_image',
                        'type' => 'image',
                        'instructions' => 'The image for this phase.',
                        'required' => 0,
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_journey_phase_order',
                        'label' => 'Phase Order',
                        'name' => 'phase_order',
                        'type' => 'select',
                        'instructions' => 'Whether the image or text appears first.',
                        'required' => 0,
                        'choices' => [
                            'image-first' => 'Image First',
                            'text-first' => 'Text First',
                        ],
                        'default_value' => 'image-first',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Process Callout Section
            [
                'key' => 'field_journey_callout_badge',
                'label' => 'Callout Badge Text',
                'name' => 'journey_callout_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the callout heading.',
                'required' => 0,
                'default_value' => 'Not Coaching',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_callout_heading',
                'label' => 'Callout Heading',
                'name' => 'journey_callout_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the callout section (first part).',
                'required' => 0,
                'default_value' => 'This Is Not Coaching.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_callout_heading_alt',
                'label' => 'Callout Heading Alt (Highlighted)',
                'name' => 'journey_callout_heading_alt',
                'type' => 'text',
                'instructions' => 'The highlighted second part of the callout heading.',
                'required' => 0,
                'default_value' => 'It\'s Transformation.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_callout_description',
                'label' => 'Callout Description',
                'name' => 'journey_callout_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the callout section.',
                'required' => 0,
                'default_value' => 'Clients often arrive expecting a structured program with deliverables and timelines. What they find is something more powerful — a process that meets them exactly where they are, surfaces what has always been true, and gives them tools to lead from it.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_callout_image',
                'label' => 'Callout Image',
                'name' => 'journey_callout_image',
                'type' => 'image',
                'instructions' => 'The image for the callout section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_callout_testimonial_quote',
                'label' => 'Callout Testimonial Quote',
                'name' => 'journey_callout_testimonial_quote',
                'type' => 'textarea',
                'instructions' => 'The testimonial quote text.',
                'required' => 0,
                'default_value' => 'At first, I honestly wanted to quit. I was expecting a traditional approach. But Joanna focused on me — on where I come from, who I am. By the end, I didn\'t just have one story. I had several. And the confidence to deliver them in a way that captivates an audience, just like a scene in a movie.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_callout_testimonial_author',
                'label' => 'Callout Testimonial Author',
                'name' => 'journey_callout_testimonial_author',
                'type' => 'text',
                'instructions' => 'The testimonial author text.',
                'required' => 0,
                'default_value' => 'Private Training Client, CEO',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Journey CTA Section
            [
                'key' => 'field_journey_cta_image',
                'label' => 'CTA Image',
                'name' => 'journey_cta_image',
                'type' => 'image',
                'instructions' => 'The image for the CTA section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_cta_badge',
                'label' => 'CTA Badge Text',
                'name' => 'journey_cta_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the CTA heading.',
                'required' => 0,
                'default_value' => 'Begin Now',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_cta_heading',
                'label' => 'CTA Heading',
                'name' => 'journey_cta_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the CTA section.',
                'required' => 0,
                'default_value' => 'Where Would You Like to Begin?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_cta_description',
                'label' => 'CTA Description',
                'name' => 'journey_cta_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the CTA section.',
                'required' => 0,
                'default_value' => 'Every journey through True Influence Method™️ starts with a conversation. Let us know where you are and where you want to go — and Joanna\'s team will guide you to the right path.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_cta_button_text',
                'label' => 'CTA Button Text',
                'name' => 'journey_cta_button_text',
                'type' => 'text',
                'instructions' => 'The text for the CTA button.',
                'required' => 0,
                'default_value' => 'Start Conversation',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_journey_cta_button_link',
                'label' => 'CTA Button Link',
                'name' => 'journey_cta_button_link',
                'type' => 'page_link',
                'instructions' => 'Select the page for the CTA button.',
                'required' => 0,
                'post_type' => ['page'],
                'taxonomy' => [],
                'allow_null' => 0,
                'multiple' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-journey.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [],
        'active' => true,
        'description' => '',
    ]);
}
