<?php

/**
 * Mastermind Page ACF Field Group
 *
 * Registers ACF fields for the mastermind page template.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_mastermind_page',
        'title' => 'Mastermind Page',
        'fields' => [
            // Hero Section
            [
                'key' => 'field_mastermind_hero_badge',
                'label' => 'Hero Badge Text',
                'name' => 'mastermind_hero_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the hero heading.',
                'required' => 0,
                'default_value' => 'Self-Guided Transformation',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_hero_heading',
                'label' => 'Hero Heading',
                'name' => 'mastermind_hero_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the hero section.',
                'required' => 0,
                'default_value' => '90-Day Mastermind',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_hero_description',
                'label' => 'Hero Description',
                'name' => 'mastermind_hero_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the hero heading.',
                'required' => 0,
                'default_value' => 'A structured journey of self-discovery and mastery. Transform your story, craft your message, and own your stage—at your own pace.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_hero_cta_text',
                'label' => 'Hero CTA Text',
                'name' => 'mastermind_hero_cta_text',
                'type' => 'text',
                'instructions' => 'The text for the hero call-to-action button.',
                'required' => 0,
                'default_value' => 'Begin Your Journey',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_hero_image',
                'label' => 'Hero Image',
                'name' => 'mastermind_hero_image',
                'type' => 'image',
                'instructions' => 'The background image for the hero section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Overview Section
            [
                'key' => 'field_mastermind_overview_badge',
                'label' => 'Overview Badge Text',
                'name' => 'mastermind_overview_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the overview heading.',
                'required' => 0,
                'default_value' => 'The Program',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_overview_heading',
                'label' => 'Overview Heading',
                'name' => 'mastermind_overview_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the overview section.',
                'required' => 0,
                'default_value' => 'Self-Study. Self-Advancement.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_overview_description',
                'label' => 'Overview Description',
                'name' => 'mastermind_overview_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the overview section.',
                'required' => 0,
                'default_value' => 'The 90-Day Mastermind is designed for leaders who value autonomy and structure. Progress through three carefully crafted phases, each building on the last, as you discover, develop, and master your authentic voice.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_overview_tagline',
                'label' => 'Overview Tagline',
                'name' => 'mastermind_overview_tagline',
                'type' => 'text',
                'instructions' => 'The tagline displayed in the badge.',
                'required' => 0,
                'default_value' => 'Your Journey, Your Timeline',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_overview_image',
                'label' => 'Overview Image',
                'name' => 'mastermind_overview_image',
                'type' => 'image',
                'instructions' => 'The image for the overview section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_features',
                'label' => 'Mastermind Features',
                'name' => 'mastermind_features',
                'type' => 'repeater',
                'instructions' => 'Add the key features of the mastermind program.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Feature',
                'sub_fields' => [
                    [
                        'key' => 'field_mastermind_feature_title',
                        'label' => 'Feature Title',
                        'name' => 'feature_title',
                        'type' => 'text',
                        'instructions' => 'The title for this feature.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Self-Guided Video Trainings',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_mastermind_feature_description',
                        'label' => 'Feature Description',
                        'name' => 'feature_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this feature.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_mastermind_feature_icon',
                        'label' => 'Feature Icon',
                        'name' => 'feature_icon',
                        'type' => 'select',
                        'instructions' => 'The icon for this feature.',
                        'required' => 0,
                        'choices' => [
                            'Play' => 'Play (Video)',
                            'BookOpen' => 'Book Open (Journal)',
                            'Users' => 'Users (Community)',
                            'Mic' => 'Microphone (Speaking)',
                            'TrendingUp' => 'Trending Up (Progress)',
                            'Crown' => 'Crown (Upgrade)',
                            'CheckCircle2' => 'Check Circle (Success)',
                            'Zap' => 'Zap (Energy)',
                            'Award' => 'Award (Achievement)',
                        ],
                        'default_value' => 'Zap',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Program Phases Section
            [
                'key' => 'field_mastermind_phases_badge',
                'label' => 'Phases Badge Text',
                'name' => 'mastermind_phases_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the phases heading.',
                'required' => 0,
                'default_value' => 'The Journey',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_phases_heading',
                'label' => 'Phases Heading',
                'name' => 'mastermind_phases_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the phases section.',
                'required' => 0,
                'default_value' => 'Three Phases to Mastery',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_phases_description',
                'label' => 'Phases Description',
                'name' => 'mastermind_phases_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the phases section.',
                'required' => 0,
                'default_value' => 'Each phase builds upon the last, creating a comprehensive path to authentic leadership communication',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_program_phases',
                'label' => 'Program Phases',
                'name' => 'mastermind_program_phases',
                'type' => 'repeater',
                'instructions' => 'Add the three phases of the program.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Phase',
                'sub_fields' => [
                    [
                        'key' => 'field_mastermind_phase_number',
                        'label' => 'Phase Number',
                        'name' => 'phase_number',
                        'type' => 'number',
                        'instructions' => 'The phase number (e.g., 1, 2, 3).',
                        'required' => 0,
                        'default_value' => 1,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => 1,
                        'max' => 10,
                        'step' => 1,
                        'wrapper' => [
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_mastermind_phase_title',
                        'label' => 'Phase Title',
                        'name' => 'phase_title',
                        'type' => 'text',
                        'instructions' => 'The title for this phase.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Foundation Phase',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '40',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_mastermind_phase_theme',
                        'label' => 'Phase Theme',
                        'name' => 'phase_theme',
                        'type' => 'text',
                        'instructions' => 'The theme for this phase.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Discover Your Story',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '40',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_mastermind_phase_duration',
                        'label' => 'Phase Duration',
                        'name' => 'phase_duration',
                        'type' => 'text',
                        'instructions' => 'The duration for this phase.',
                        'required' => 0,
                        'default_value' => '30 Days',
                        'placeholder' => 'e.g., 30 Days',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '40',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_mastermind_phase_focus',
                        'label' => 'Phase Focus',
                        'name' => 'phase_focus',
                        'type' => 'textarea',
                        'instructions' => 'The focus description for this phase.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_mastermind_phase_color',
                        'label' => 'Phase Color',
                        'name' => 'phase_color',
                        'type' => 'text',
                        'instructions' => 'The gradient color for this phase (e.g., from-purple-900/20 to-purple-900/5).',
                        'required' => 0,
                        'default_value' => 'from-purple-900/20 to-purple-900/5',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_mastermind_phase_border',
                        'label' => 'Phase Border',
                        'name' => 'phase_border',
                        'type' => 'text',
                        'instructions' => 'The border color for this phase (e.g., border-purple-500/30).',
                        'required' => 0,
                        'default_value' => 'border-purple-500/30',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_mastermind_phase_accent',
                        'label' => 'Phase Accent',
                        'name' => 'phase_accent',
                        'type' => 'text',
                        'instructions' => 'The accent text color for this phase (e.g., text-purple-400).',
                        'required' => 0,
                        'default_value' => 'text-purple-400',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_mastermind_phase_trainings',
                        'label' => 'Phase Trainings',
                        'name' => 'phase_trainings',
                        'type' => 'repeater',
                        'instructions' => 'Add the video trainings for this phase.',
                        'required' => 0,
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => 'Add Training',
                        'sub_fields' => [
                            [
                                'key' => 'field_mastermind_training_title',
                                'label' => 'Training Title',
                                'name' => 'training_title',
                                'type' => 'text',
                                'instructions' => 'The title of the training.',
                                'required' => 0,
                                'default_value' => '',
                                'placeholder' => 'e.g., Naming Your Story',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // What's Included Section
            [
                'key' => 'field_mastermind_included_badge',
                'label' => 'Included Badge Text',
                'name' => 'mastermind_included_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the included heading.',
                'required' => 0,
                'default_value' => 'What You Receive',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_included_heading',
                'label' => 'Included Heading',
                'name' => 'mastermind_included_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the included section.',
                'required' => 0,
                'default_value' => 'Everything You Need to Succeed',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_included_description',
                'label' => 'Included Description',
                'name' => 'mastermind_included_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the included section.',
                'required' => 0,
                'default_value' => 'A complete toolkit designed to support your transformation from start to finish',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_included_image',
                'label' => 'Included Image',
                'name' => 'mastermind_included_image',
                'type' => 'image',
                'instructions' => 'The image for the included section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_included_items',
                'label' => 'Included Items',
                'name' => 'mastermind_included_items',
                'type' => 'repeater',
                'instructions' => 'Add the items included in the program.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Item',
                'sub_fields' => [
                    [
                        'key' => 'field_mastermind_included_item_title',
                        'label' => 'Item Title',
                        'name' => 'included_item_title',
                        'type' => 'text',
                        'instructions' => 'The title for this item.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Complete Video Library',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_mastermind_included_item_description',
                        'label' => 'Item Description',
                        'name' => 'included_item_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this item.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_mastermind_included_item_icon',
                        'label' => 'Item Icon',
                        'name' => 'included_item_icon',
                        'type' => 'select',
                        'instructions' => 'The icon for this item.',
                        'required' => 0,
                        'choices' => [
                            'Play' => 'Play (Video)',
                            'BookOpen' => 'Book Open (Journal)',
                            'Users' => 'Users (Community)',
                            'Mic' => 'Microphone (Speaking)',
                            'TrendingUp' => 'Trending Up (Progress)',
                            'Crown' => 'Crown (Upgrade)',
                            'CheckCircle2' => 'Check Circle (Success)',
                            'Zap' => 'Zap (Energy)',
                            'Award' => 'Award (Achievement)',
                        ],
                        'default_value' => 'Zap',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Advancement Section
            [
                'key' => 'field_mastermind_advancement_badge',
                'label' => 'Advancement Badge Text',
                'name' => 'mastermind_advancement_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the advancement heading.',
                'required' => 0,
                'default_value' => 'How You Advance',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_advancement_heading',
                'label' => 'Advancement Heading',
                'name' => 'mastermind_advancement_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the advancement section.',
                'required' => 0,
                'default_value' => 'Earn Your Progress',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_advancement_description',
                'label' => 'Advancement Description',
                'name' => 'mastermind_advancement_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the advancement section.',
                'required' => 0,
                'default_value' => 'Advancement is earned through engagement and demonstrated understanding. Each phase has clear criteria you must meet before moving forward.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_advancement_criteria',
                'label' => 'Advancement Criteria',
                'name' => 'mastermind_advancement_criteria',
                'type' => 'repeater',
                'instructions' => 'Add the advancement criteria items.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Criterion',
                'sub_fields' => [
                    [
                        'key' => 'field_mastermind_criterion_title',
                        'label' => 'Criterion Title',
                        'name' => 'criterion_title',
                        'type' => 'text',
                        'instructions' => 'The title for this criterion.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Complete All Trainings',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_mastermind_criterion_description',
                        'label' => 'Criterion Description',
                        'name' => 'criterion_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this criterion.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_rubric_title',
                'label' => 'Rubric Box Title',
                'name' => 'mastermind_rubric_title',
                'type' => 'text',
                'instructions' => 'The title for the rubric box.',
                'required' => 0,
                'default_value' => 'The Rubric System',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_rubric_description',
                'label' => 'Rubric Box Description',
                'name' => 'mastermind_rubric_description',
                'type' => 'textarea',
                'instructions' => 'The description for the rubric box.',
                'required' => 0,
                'default_value' => 'Each phase concludes with a self-assessment rubric that measures your understanding and application of key concepts. This ensures you\'ve genuinely integrated the learning before advancing—creating a foundation that builds confidence and capability.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_rubric_note',
                'label' => 'Rubric Box Note',
                'name' => 'mastermind_rubric_note',
                'type' => 'text',
                'instructions' => 'The note text displayed at the bottom of the rubric box.',
                'required' => 0,
                'default_value' => 'Pass the rubric to unlock the next phase',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Why This Works Section
            [
                'key' => 'field_mastermind_why_badge',
                'label' => 'Why Badge Text',
                'name' => 'mastermind_why_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the why heading.',
                'required' => 0,
                'default_value' => 'Why This Works',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_why_heading',
                'label' => 'Why Heading',
                'name' => 'mastermind_why_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the why section.',
                'required' => 0,
                'default_value' => 'A Proven Path to Transformation',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_why_description',
                'label' => 'Why Description',
                'name' => 'mastermind_why_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the why section.',
                'required' => 0,
                'default_value' => 'The 90-Day Mastermind combines structure, community, and accountability to create lasting change in how you communicate and lead.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_why_image',
                'label' => 'Why Image',
                'name' => 'mastermind_why_image',
                'type' => 'image',
                'instructions' => 'The image for the why section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_why_benefits',
                'label' => 'Why Benefits',
                'name' => 'mastermind_why_benefits',
                'type' => 'repeater',
                'instructions' => 'Add the benefits of the program.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Benefit',
                'sub_fields' => [
                    [
                        'key' => 'field_mastermind_benefit_title',
                        'label' => 'Benefit Title',
                        'name' => 'benefit_title',
                        'type' => 'text',
                        'instructions' => 'The title for this benefit.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Structured Progression',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_mastermind_benefit_description',
                        'label' => 'Benefit Description',
                        'name' => 'benefit_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this benefit.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_mastermind_benefit_icon',
                        'label' => 'Benefit Icon',
                        'name' => 'benefit_icon',
                        'type' => 'select',
                        'instructions' => 'The icon for this benefit.',
                        'required' => 0,
                        'choices' => [
                            'Star' => 'Star',
                            'Users' => 'Users',
                            'TrendingUp' => 'Trending Up',
                            'BookOpen' => 'Book Open',
                            'Mic' => 'Microphone',
                            'Award' => 'Award',
                        ],
                        'default_value' => 'Star',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Upgrade Path Section
            [
                'key' => 'field_mastermind_upgrade_badge',
                'label' => 'Upgrade Badge Text',
                'name' => 'mastermind_upgrade_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the upgrade heading.',
                'required' => 0,
                'default_value' => 'Your Options',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_upgrade_heading',
                'label' => 'Upgrade Heading',
                'name' => 'mastermind_upgrade_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the upgrade section.',
                'required' => 0,
                'default_value' => 'Want More?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_upgrade_description',
                'label' => 'Upgrade Description',
                'name' => 'mastermind_upgrade_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the upgrade section.',
                'required' => 0,
                'default_value' => 'The Mastermind is a powerful foundation. When you\'re ready for deeper transformation, you can upgrade to Private Client at any time.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_mastermind_title',
                'label' => 'Mastermind Card Title',
                'name' => 'mastermind_mastermind_title',
                'type' => 'text',
                'instructions' => 'The title for the mastermind card.',
                'required' => 0,
                'default_value' => '90-Day Mastermind',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_mastermind_features',
                'label' => 'Mastermind Card Features',
                'name' => 'mastermind_mastermind_features',
                'type' => 'repeater',
                'instructions' => 'Add the features for the mastermind card.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add Feature',
                'sub_fields' => [
                    [
                        'key' => 'field_mastermind_mastermind_feature_text',
                        'label' => 'Feature Text',
                        'name' => 'mastermind_feature_text',
                        'type' => 'text',
                        'instructions' => 'The feature text.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Self-guided video trainings',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_mastermind_note',
                'label' => 'Mastermind Card Note',
                'name' => 'mastermind_mastermind_note',
                'type' => 'text',
                'instructions' => 'The note text at the bottom of the mastermind card.',
                'required' => 0,
                'default_value' => 'Self-paced, self-directed learning',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_private_title',
                'label' => 'Private Client Card Title',
                'name' => 'mastermind_private_title',
                'type' => 'text',
                'instructions' => 'The title for the private client card.',
                'required' => 0,
                'default_value' => 'Upgrade to Private Client',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_private_features',
                'label' => 'Private Client Card Features',
                'name' => 'mastermind_private_features',
                'type' => 'repeater',
                'instructions' => 'Add the features for the private client card.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add Feature',
                'sub_fields' => [
                    [
                        'key' => 'field_mastermind_private_feature_text',
                        'label' => 'Feature Text',
                        'name' => 'private_feature_text',
                        'type' => 'text',
                        'instructions' => 'The feature text.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Everything in Mastermind',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_private_note',
                'label' => 'Private Client Card Note',
                'name' => 'mastermind_private_note',
                'type' => 'text',
                'instructions' => 'The note text at the bottom of the private client card.',
                'required' => 0,
                'default_value' => 'Upgrade available at any time',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // CTA Section
            [
                'key' => 'field_mastermind_cta_badge',
                'label' => 'CTA Badge Text',
                'name' => 'mastermind_cta_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the CTA heading.',
                'required' => 0,
                'default_value' => 'Your Transformation Begins',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_cta_heading',
                'label' => 'CTA Heading',
                'name' => 'mastermind_cta_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the CTA section.',
                'required' => 0,
                'default_value' => 'Ready to Find Your Voice?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_cta_description',
                'label' => 'CTA Description',
                'name' => 'mastermind_cta_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the CTA section.',
                'required' => 0,
                'default_value' => 'The 90-Day Mastermind gives you the structure, tools, and community to transform your story into powerful leadership communication. Begin your journey today.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_cta_button_text',
                'label' => 'CTA Button Text',
                'name' => 'mastermind_cta_button_text',
                'type' => 'text',
                'instructions' => 'The text for the CTA button.',
                'required' => 0,
                'default_value' => 'Start Your Journey',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_cta_quote',
                'label' => 'CTA Quote',
                'name' => 'mastermind_cta_quote',
                'type' => 'textarea',
                'instructions' => 'The quote text displayed in the quote box.',
                'required' => 0,
                'default_value' => 'The path to authentic influence isn\'t found—it\'s forged through courage, practice, and the willingness to be seen.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_mastermind_cta_image',
                'label' => 'CTA Image',
                'name' => 'mastermind_cta_image',
                'type' => 'image',
                'instructions' => 'The image for the CTA section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ],
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-mastermind.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [],
        'active' => true,
        'description' => '',
    ]);
}
