<?php

/**
 * Media Page ACF Field Group
 *
 * Registers ACF fields for the media landing page template.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_media_page',
        'title' => 'Media Page',
        'fields' => [
            // Hero Section
            [
                'key' => 'field_media_hero_badge',
                'label' => 'Hero Badge Text',
                'name' => 'media_hero_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the hero heading.',
                'required' => 0,
                'default_value' => 'In The Spotlight',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_media_hero_heading',
                'label' => 'Hero Heading',
                'name' => 'media_hero_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the hero section.',
                'required' => 0,
                'default_value' => 'Media Features & Interviews',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_media_hero_description',
                'label' => 'Hero Description',
                'name' => 'media_hero_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the hero heading.',
                'required' => 0,
                'default_value' => 'Joanna has been featured in leading publications and podcasts, sharing her expertise on leadership communication and authentic influence with audiences worldwide.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_media_hero_cta_text',
                'label' => 'Hero CTA Text',
                'name' => 'media_hero_cta_text',
                'type' => 'text',
                'instructions' => 'The text for the call-to-action button.',
                'required' => 0,
                'default_value' => 'View Features',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_media_hero_cta_link',
                'label' => 'Hero CTA Link',
                'name' => 'media_hero_cta_link',
                'type' => 'page_link',
                'instructions' => 'Select the page for the call-to-action button.',
                'required' => 0,
                'post_type' => ['page'],
                'taxonomy' => [],
                'allow_null' => 1,
                'multiple' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Featured Section
            [
                'key' => 'field_media_featured_badge',
                'label' => 'Featured Badge Text',
                'name' => 'media_featured_badge',
                'type' => 'text',
                'instructions' => 'The badge text for the featured section.',
                'required' => 0,
                'default_value' => 'Recent Features',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_media_featured_heading',
                'label' => 'Featured Section Heading',
                'name' => 'media_featured_heading',
                'type' => 'text',
                'instructions' => 'The heading text for the featured section.',
                'required' => 0,
                'default_value' => 'Latest Media Appearances',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_media_featured_description',
                'label' => 'Featured Section Description',
                'name' => 'media_featured_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the featured section.',
                'required' => 0,
                'default_value' => 'See where Joanna has been featured recently, sharing her insights on leadership and communication.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Grid Section
            [
                'key' => 'field_media_grid_badge',
                'label' => 'Grid Badge Text',
                'name' => 'media_grid_badge',
                'type' => 'text',
                'instructions' => 'The badge text for the grid section.',
                'required' => 0,
                'default_value' => 'All Features',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_media_grid_heading',
                'label' => 'Grid Section Heading',
                'name' => 'media_grid_heading',
                'type' => 'text',
                'instructions' => 'The heading text for the grid section.',
                'required' => 0,
                'default_value' => 'Full Media Archive',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_media_grid_description',
                'label' => 'Grid Section Description',
                'name' => 'media_grid_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the grid section.',
                'required' => 0,
                'default_value' => 'Browse all of Joanna\'s media features, interviews, and guest appearances.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-media.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [
            'the_content',
            'excerpt',
            'discussion',
            'comments',
            'revisions',
            'slug',
            'author',
            'format',
            'page_attributes',
            'featured_image',
            'categories',
            'tags',
            'send-trackbacks',
        ],
        'active' => true,
        'description' => 'ACF fields for the Media landing page template.',
    ]);
}
