<?php

/**
 * Paths Section ACF Field Group
 *
 * Registers ACF fields for the paths section on the front page.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_paths_section',
        'title' => 'Paths Section',
        'fields' => [
            [
                'key' => 'field_paths_badge_text',
                'label' => 'Badge Text',
                'name' => 'paths_badge_text',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the heading.',
                'required' => 0,
                'default_value' => 'Ways to Work Together',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_paths_heading',
                'label' => 'Section Heading',
                'name' => 'paths_heading',
                'type' => 'text',
                'instructions' => 'The main heading for the paths section.',
                'required' => 0,
                'default_value' => 'One Method. Three Paths.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_paths_description',
                'label' => 'Section Description',
                'name' => 'paths_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the paths section.',
                'required' => 0,
                'default_value' => "Whether you're a CEO ready for private mastery, a rising leader joining a powerful group, or an organization building a culture of courageous communication — there is a path for you.",
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_paths_items',
                'label' => 'Paths',
                'name' => 'paths_items',
                'type' => 'repeater',
                'instructions' => 'Add path items (Private Training, Speak & Rise, Corporate Programs).',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 3,
                'layout' => 'block',
                'button_label' => 'Add Path',
                'sub_fields' => [
                    [
                        'key' => 'field_path_icon',
                        'label' => 'Icon',
                        'name' => 'path_icon',
                        'type' => 'select',
                        'instructions' => 'Select the icon for this path.',
                        'required' => 0,
                        'choices' => [
                            'user' => 'User (Person)',
                            'users' => 'Users (Group)',
                            'building' => 'Building (Corporate)',
                        ],
                        'default_value' => 'user',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_path_title',
                        'label' => 'Path Title',
                        'name' => 'path_title',
                        'type' => 'text',
                        'instructions' => 'The title for this path.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Private Training',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '67',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_path_description',
                        'label' => 'Path Description',
                        'name' => 'path_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this path.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'Describe what this path offers...',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_path_price',
                        'label' => 'Price',
                        'name' => 'path_price',
                        'type' => 'text',
                        'instructions' => 'The price for this path.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., From $20,000',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_path_role',
                        'label' => 'Role Badge',
                        'name' => 'path_role',
                        'type' => 'text',
                        'instructions' => 'The role badge text (e.g., Student, Client, Exclusive).',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Student',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_path_cta_text',
                        'label' => 'CTA Button Text',
                        'name' => 'path_cta_text',
                        'type' => 'text',
                        'instructions' => 'The text for the call-to-action button.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Apply for Private Training',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_path_cta_link',
                        'label' => 'CTA Link',
                        'name' => 'path_cta_link',
                        'type' => 'link',
                        'instructions' => 'Select the page or enter a URL for the call-to-action button.',
                        'required' => 0,
                        'return_format' => 'array',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_path_features',
                        'label' => 'Features',
                        'name' => 'path_features',
                        'type' => 'repeater',
                        'instructions' => 'Add features for this path.',
                        'required' => 0,
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => 'Add Feature',
                        'sub_fields' => [
                            [
                                'key' => 'field_path_feature_text',
                                'label' => 'Feature Text',
                                'name' => 'feature_text',
                                'type' => 'text',
                                'instructions' => 'The feature text.',
                                'required' => 0,
                                'default_value' => '',
                                'placeholder' => 'e.g., One-on-one sessions with Joanna',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'front-page.php',
                ],
            ],
        ],
        'menu_order' => 2,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [],
        'active' => true,
        'description' => 'Configure the paths section content for the front page.',
    ]);
}
