<?php

/**
 * Private Training Page ACF Field Group
 *
 * Registers ACF fields for the private training page template.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_private_training_page',
        'title' => 'Private Training Page',
        'fields' => [
            // Hero Section
            [
                'key' => 'field_private_training_hero_badge',
                'label' => 'Hero Badge Text',
                'name' => 'private_training_hero_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the hero heading.',
                'required' => 0,
                'default_value' => 'Private Client Experience',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_hero_heading',
                'label' => 'Hero Heading',
                'name' => 'private_training_hero_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the hero section.',
                'required' => 0,
                'default_value' => 'Your Transformative Partnership',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_hero_description',
                'label' => 'Hero Description',
                'name' => 'private_training_hero_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the hero heading.',
                'required' => 0,
                'default_value' => 'Everything in the Mastermind track, plus private advisory sessions, individualized training paths, and transformative, personalized insights. Auto-enrolled in Kajabi course portal. Phases 4 & 5 by application only. Pay phase-by-phase or in bundled packages.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_hero_image',
                'label' => 'Hero Image',
                'name' => 'private_training_hero_image',
                'type' => 'image',
                'instructions' => 'The background image for the hero section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Introduction Section
            [
                'key' => 'field_private_training_intro_badge',
                'label' => 'Introduction Badge Text',
                'name' => 'private_training_intro_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the introduction heading.',
                'required' => 0,
                'default_value' => 'Private Client Experience',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_intro_heading',
                'label' => 'Introduction Heading',
                'name' => 'private_training_intro_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the introduction section.',
                'required' => 0,
                'default_value' => 'Your Transformative Partnership',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_intro_description',
                'label' => 'Introduction Description',
                'name' => 'private_training_intro_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the introduction section.',
                'required' => 0,
                'default_value' => 'Private clients receive everything in the Mastermind track, plus private advisory sessions with Joanna, an individualized training path, and transformative, personalized insights designed to accelerate your growth.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_intro_left_paragraph_1',
                'label' => 'Introduction Left Paragraph 1',
                'name' => 'private_training_intro_left_paragraph_1',
                'type' => 'textarea',
                'instructions' => 'The first paragraph in the left column of the introduction section.',
                'required' => 0,
                'default_value' => 'This exclusive, high-touch experience is crafted for leaders ready to step fully into their power. Through private advisory sessions and a tailored individualized training path, Joanna delivers transformative insights that unlock your authentic voice and amplify your impact.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_intro_left_paragraph_2',
                'label' => 'Introduction Left Paragraph 2',
                'name' => 'private_training_intro_left_paragraph_2',
                'type' => 'textarea',
                'instructions' => 'The second paragraph in the left column of the introduction section.',
                'required' => 0,
                'default_value' => 'You\'ll gain seamless access to all resources through auto-enrollment in the Kajabi course portal. Phases 4 & 5 are available by application only for those seeking the deepest level of transformation. Choose to pay phase-by-phase or in bundled packages for maximum flexibility.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_intro_image',
                'label' => 'Introduction Image',
                'name' => 'private_training_intro_image',
                'type' => 'image',
                'instructions' => 'The image for the introduction section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Identifying Your Block Section (Step 1)
            [
                'key' => 'field_private_training_step1_badge',
                'label' => 'Step 1 Badge Text',
                'name' => 'private_training_step1_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the Step 1 heading.',
                'required' => 0,
                'default_value' => 'Step 1: Identify Your Block',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step1_heading',
                'label' => 'Step 1 Heading',
                'name' => 'private_training_step1_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the Step 1 section.',
                'required' => 0,
                'default_value' => 'Where Are You on Your Story Journey?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step1_description',
                'label' => 'Step 1 Description',
                'name' => 'private_training_step1_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the Step 1 section.',
                'required' => 0,
                'default_value' => 'Your Private Client Experience begins with clarity. Understanding where you are now helps Joanna design your individualized training path and deliver transformative, personalized insights.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step1_blocks',
                'label' => 'Step 1 Blocks',
                'name' => 'private_training_step1_blocks',
                'type' => 'repeater',
                'instructions' => 'Add the blocks for Step 1.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Block',
                'sub_fields' => [
                    [
                        'key' => 'field_private_training_step1_block_title',
                        'label' => 'Block Title',
                        'name' => 'block_title',
                        'type' => 'text',
                        'instructions' => 'The title for this block.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Fear & Anxiety',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_private_training_step1_block_description',
                        'label' => 'Block Description',
                        'name' => 'block_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this block.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_private_training_step1_block_icon',
                        'label' => 'Block Icon',
                        'name' => 'block_icon',
                        'type' => 'select',
                        'instructions' => 'The icon for this block.',
                        'required' => 0,
                        'choices' => [
                            'Target' => 'Target',
                            'Users' => 'Users',
                            'BookOpen' => 'Book Open',
                            'Shield' => 'Shield',
                            'Zap' => 'Zap',
                            'CheckCircle2' => 'Check Circle',
                            'ArrowRight' => 'Arrow Right',
                        ],
                        'default_value' => 'Target',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // The Vision Section (Step 2)
            [
                'key' => 'field_private_training_step2_badge',
                'label' => 'Step 2 Badge Text',
                'name' => 'private_training_step2_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the Step 2 heading.',
                'required' => 0,
                'default_value' => 'Step 2: Clarify Your Vision',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step2_heading',
                'label' => 'Step 2 Heading',
                'name' => 'private_training_step2_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the Step 2 section.',
                'required' => 0,
                'default_value' => 'What Transformation Are You Seeking?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step2_description',
                'label' => 'Step 2 Description',
                'name' => 'private_training_step2_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the Step 2 section.',
                'required' => 0,
                'default_value' => 'Your Private Client Experience is designed around your unique aspirations. Understanding your vision helps Joanna craft your individualized training path and deliver transformative, personalized insights.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step2_visions',
                'label' => 'Step 2 Visions',
                'name' => 'private_training_step2_visions',
                'type' => 'repeater',
                'instructions' => 'Add the vision items for Step 2.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Vision',
                'sub_fields' => [
                    [
                        'key' => 'field_private_training_step2_vision_text',
                        'label' => 'Vision Text',
                        'name' => 'vision_text',
                        'type' => 'text',
                        'instructions' => 'The text for this vision.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Elevate my brand authority and market presence.',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Outcomes Section (Step 3)
            [
                'key' => 'field_private_training_step3_badge',
                'label' => 'Step 3 Badge Text',
                'name' => 'private_training_step3_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the Step 3 heading.',
                'required' => 0,
                'default_value' => 'Step 3: Define Success',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step3_heading',
                'label' => 'Step 3 Heading',
                'name' => 'private_training_step3_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the Step 3 section.',
                'required' => 0,
                'default_value' => 'What Does "Success" Look Like for You?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step3_description',
                'label' => 'Step 3 Description',
                'name' => 'private_training_step3_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the Step 3 section.',
                'required' => 0,
                'default_value' => 'We translate vision into tangible outcomes. Here\'s what private clients achieve through their individualized training path.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step3_outcomes',
                'label' => 'Step 3 Outcomes',
                'name' => 'private_training_step3_outcomes',
                'type' => 'repeater',
                'instructions' => 'Add the outcomes for Step 3.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Outcome',
                'sub_fields' => [
                    [
                        'key' => 'field_private_training_step3_outcome_title',
                        'label' => 'Outcome Title',
                        'name' => 'outcome_title',
                        'type' => 'text',
                        'instructions' => 'The title for this outcome.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Clarity in Message',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_private_training_step3_outcome_description',
                        'label' => 'Outcome Description',
                        'name' => 'outcome_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this outcome.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Professional Path Section (Step 4)
            [
                'key' => 'field_private_training_step4_badge',
                'label' => 'Step 4 Badge Text',
                'name' => 'private_training_step4_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the Step 4 heading.',
                'required' => 0,
                'default_value' => 'Step 4: Your Professional Path',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step4_heading',
                'label' => 'Step 4 Heading',
                'name' => 'private_training_step4_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the Step 4 section.',
                'required' => 0,
                'default_value' => 'Which Best Describes Your Current Professional Path?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step4_description',
                'label' => 'Step 4 Description',
                'name' => 'private_training_step4_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the Step 4 section.',
                'required' => 0,
                'default_value' => 'Private training is customized to your role, ambition, and legacy.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step4_paths',
                'label' => 'Step 4 Paths',
                'name' => 'private_training_step4_paths',
                'type' => 'repeater',
                'instructions' => 'Add the professional paths for Step 4.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Path',
                'sub_fields' => [
                    [
                        'key' => 'field_private_training_step4_path_title',
                        'label' => 'Path Title',
                        'name' => 'path_title',
                        'type' => 'text',
                        'instructions' => 'The title for this path.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Emerging Leader/Entrepreneur',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_private_training_step4_path_description',
                        'label' => 'Path Description',
                        'name' => 'path_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this path.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Investment & Alignment Section (Step 5)
            [
                'key' => 'field_private_training_step5_badge',
                'label' => 'Step 5 Badge Text',
                'name' => 'private_training_step5_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the Step 5 heading.',
                'required' => 0,
                'default_value' => 'Step 5: Investment & Alignment',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step5_heading',
                'label' => 'Step 5 Heading',
                'name' => 'private_training_step5_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the Step 5 section.',
                'required' => 0,
                'default_value' => 'Choose Your Level of Transformation',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step5_description',
                'label' => 'Step 5 Description',
                'name' => 'private_training_step5_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the Step 5 section.',
                'required' => 0,
                'default_value' => 'Private clients receive everything in the Mastermind track, plus private 1:1 advisory sessions with Joanna. Choose to pay phase-by-phase or in bundled packages. Phases 4 & 5 are available by application only.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step5_investments',
                'label' => 'Step 5 Investment Options',
                'name' => 'private_training_step5_investments',
                'type' => 'repeater',
                'instructions' => 'Add the investment options for Step 5.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Investment Option',
                'sub_fields' => [
                    [
                        'key' => 'field_private_training_step5_investment_level',
                        'label' => 'Investment Level',
                        'name' => 'investment_level',
                        'type' => 'text',
                        'instructions' => 'The level for this investment (e.g., Phase 1-3, Phase 1-5).',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Phase 1-3',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_private_training_step5_investment_name',
                        'label' => 'Investment Name',
                        'name' => 'investment_name',
                        'type' => 'text',
                        'instructions' => 'The name for this investment.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Private Client Experience',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_private_training_step5_investment_price',
                        'label' => 'Investment Price',
                        'name' => 'investment_price',
                        'type' => 'text',
                        'instructions' => 'The price for this investment.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., $20,000',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_private_training_step5_investment_description',
                        'label' => 'Investment Description',
                        'name' => 'investment_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this investment.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_private_training_step5_investment_icon',
                        'label' => 'Investment Icon',
                        'name' => 'investment_icon',
                        'type' => 'select',
                        'instructions' => 'The icon for this investment.',
                        'required' => 0,
                        'choices' => [
                            'Target' => 'Target',
                            'Users' => 'Users',
                            'BookOpen' => 'Book Open',
                            'Shield' => 'Shield',
                            'Zap' => 'Zap',
                            'CheckCircle2' => 'Check Circle',
                            'ArrowRight' => 'Arrow Right',
                        ],
                        'default_value' => 'Target',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_private_training_step5_investment_popular',
                        'label' => 'Mark as Popular',
                        'name' => 'investment_popular',
                        'type' => 'true_false',
                        'instructions' => 'Check to highlight this investment option as popular.',
                        'required' => 0,
                        'default_value' => 0,
                        'message' => 'Mark as Popular',
                        'ui' => 1,
                        'ui_on_text' => 'Yes',
                        'ui_off_text' => 'No',
                        'wrapper' => [
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step5_footer_note',
                'label' => 'Step 5 Footer Note',
                'name' => 'private_training_step5_footer_note',
                'type' => 'textarea',
                'instructions' => 'The footer note displayed below the investment options.',
                'required' => 0,
                'default_value' => 'Note: All private clients receive direct access to Joanna, invitation to quarterly Mastermind & Retreat experiences, auto-enrollment in the Kajabi course portal, a lifetime messaging foundation, and access to The Vault resource library.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // The Find Your Story Call Section (Step 6)
            [
                'key' => 'field_private_training_step6_badge',
                'label' => 'Step 6 Badge Text',
                'name' => 'private_training_step6_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the Step 6 heading.',
                'required' => 0,
                'default_value' => 'Step 6: The Find Your Story Call',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step6_heading',
                'label' => 'Step 6 Heading',
                'name' => 'private_training_step6_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the Step 6 section.',
                'required' => 0,
                'default_value' => 'Your First Step Is a Conversation with Joanna',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step6_description',
                'label' => 'Step 6 Description',
                'name' => 'private_training_step6_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the Step 6 section.',
                'required' => 0,
                'default_value' => 'If you plan to join the Private Client Experience, the first step is meeting with Joanna. This is not a sales call—it\'s the beginning of your individualized training path.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step6_success_box_title',
                'label' => 'Step 6 Success Box Title',
                'name' => 'private_training_step6_success_box_title',
                'type' => 'text',
                'instructions' => 'The title for the success box.',
                'required' => 0,
                'default_value' => 'Success Starts Now',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step6_success_box_content',
                'label' => 'Step 6 Success Box Content',
                'name' => 'private_training_step6_success_box_content',
                'type' => 'wysiwyg',
                'instructions' => 'The content for the success box.',
                'required' => 0,
                'default_value' => '<p>Marianne suggested that Joanna "do the first lesson" (Naming the Story) during the discovery call.</p><p>On the "Thank You" page after you submit your inquiry, we include a note:<br><em class="text-[#d4b478]">"Success starts now. In our upcoming call, we will move past the \'talk\' and immediately begin the work of Naming Your Story. Please come prepared to dive deep."</em></p>',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step6_additional_paragraph',
                'label' => 'Step 6 Additional Paragraph',
                'name' => 'private_training_step6_additional_paragraph',
                'type' => 'textarea',
                'instructions' => 'The additional paragraph below the success box.',
                'required' => 0,
                'default_value' => 'Bring any questions, hesitations, or excitement. This call is your opportunity to see if this is the right container for your growth—and for Joanna to assess alignment.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_step6_image',
                'label' => 'Step 6 Image',
                'name' => 'private_training_step6_image',
                'type' => 'image',
                'instructions' => 'The image for the Step 6 section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // CTA Section
            [
                'key' => 'field_private_training_cta_badge',
                'label' => 'CTA Badge Text',
                'name' => 'private_training_cta_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the CTA heading.',
                'required' => 0,
                'default_value' => 'Ready to Begin?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_cta_heading',
                'label' => 'CTA Heading',
                'name' => 'private_training_cta_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the CTA section.',
                'required' => 0,
                'default_value' => 'Apply for Private Client Experience',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_cta_description',
                'label' => 'CTA Description',
                'name' => 'private_training_cta_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the CTA section.',
                'required' => 0,
                'default_value' => 'If you\'ve read this far, you\'re likely a high‑alignment lead. The next step is to submit your essentials—name, email, phone—and schedule your Find Your Story call. Choose to pay phase-by-phase or in bundled packages.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_cta_button_text',
                'label' => 'CTA Button Text',
                'name' => 'private_training_cta_button_text',
                'type' => 'text',
                'instructions' => 'The text for the primary CTA button.',
                'required' => 0,
                'default_value' => 'Apply Now',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_cta_secondary_button_text',
                'label' => 'CTA Secondary Button Text',
                'name' => 'private_training_cta_secondary_button_text',
                'type' => 'text',
                'instructions' => 'The text for the secondary CTA button.',
                'required' => 0,
                'default_value' => 'Explore All Programs',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_private_training_cta_footer_note',
                'label' => 'CTA Footer Note',
                'name' => 'private_training_cta_footer_note',
                'type' => 'textarea',
                'instructions' => 'The footer note displayed below the CTA buttons.',
                'required' => 0,
                'default_value' => 'No forms on this page—just the details. When you\'re ready, the application awaits.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ],
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-private-training.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [],
        'active' => true,
        'description' => '',
    ]);
}
