<?php

/**
 * Programs Page ACF Field Group
 *
 * Registers ACF fields for the programs page template.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_programs_page',
        'title' => 'Programs Page',
        'fields' => [
            // Hero Section
            [
                'key' => 'field_programs_hero_badge',
                'label' => 'Hero Badge Text',
                'name' => 'programs_hero_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the hero heading.',
                'required' => 0,
                'default_value' => 'Programs',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_hero_heading',
                'label' => 'Hero Heading',
                'name' => 'programs_hero_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the hero section.',
                'required' => 0,
                'default_value' => 'Three Offers. One Method. Transformation at Every Level.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_hero_description',
                'label' => 'Hero Description',
                'name' => 'programs_hero_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the hero heading.',
                'required' => 0,
                'default_value' => 'Joanna offers three distinct paths into True Influence Method™️ — each designed for a different context, depth, and investment. All three are grounded in same rigorous process. All three create lasting change.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Private Training Section
            [
                'key' => 'field_programs_private_badge',
                'label' => 'Private Training Badge Text',
                'name' => 'programs_private_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the private training heading.',
                'required' => 0,
                'default_value' => 'Flagship Offer · Private Clients',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_private_heading',
                'label' => 'Private Training Heading',
                'name' => 'programs_private_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the private training section.',
                'required' => 0,
                'default_value' => 'Private Training: The Deepest Work Joanna Does.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_private_description_1',
                'label' => 'Private Training Description 1',
                'name' => 'programs_private_description_1',
                'type' => 'textarea',
                'instructions' => 'The first description paragraph for the private training section.',
                'required' => 0,
                'default_value' => 'Designed for founders, CEOs, and executives who are ready to own their message, develop their signature story, and step fully into thought leadership. This is one-on-one, high-touch, and entirely bespoke.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_private_description_2',
                'label' => 'Private Training Description 2',
                'name' => 'programs_private_description_2',
                'type' => 'textarea',
                'instructions' => 'The second description paragraph for the private training section.',
                'required' => 0,
                'default_value' => 'Private clients work directly with Joanna in a structured 90-day engagement — and join her exclusive quarterly Mastermind & Retreat throughout the time they work together.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_private_levels_heading',
                'label' => 'Private Training Levels Heading',
                'name' => 'programs_private_levels_heading',
                'type' => 'text',
                'instructions' => 'The heading text for the three levels of private training.',
                'required' => 0,
                'default_value' => 'Three Levels of Private Training:',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_private_levels',
                'label' => 'Private Training Levels',
                'name' => 'programs_private_levels',
                'type' => 'repeater',
                'instructions' => 'Add the three levels of private training programs.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Level',
                'sub_fields' => [
                    [
                        'key' => 'field_programs_private_level_name',
                        'label' => 'Level Name',
                        'name' => 'level_name',
                        'type' => 'text',
                        'instructions' => 'The level name (e.g., Beginning, Intermediate, Advanced).',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Beginning',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_programs_private_level_title',
                        'label' => 'Level Title',
                        'name' => 'level_title',
                        'type' => 'text',
                        'instructions' => 'The title for this level (e.g., Tell Your Story).',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Tell Your Story',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_programs_private_level_price',
                        'label' => 'Level Price',
                        'name' => 'level_price',
                        'type' => 'text',
                        'instructions' => 'The price for this level (e.g., $20,000).',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., $20,000',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_programs_private_level_description',
                        'label' => 'Level Description',
                        'name' => 'level_description',
                        'type' => 'textarea',
                        'instructions' => 'The description for this level.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_private_benefits_heading',
                'label' => 'Private Training Benefits Heading',
                'name' => 'programs_private_benefits_heading',
                'type' => 'text',
                'instructions' => 'The heading text for the private training benefits section.',
                'required' => 0,
                'default_value' => 'All private clients receive:',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_private_benefits',
                'label' => 'Private Training Benefits',
                'name' => 'programs_private_benefits',
                'type' => 'repeater',
                'instructions' => 'Add the benefits that all private clients receive.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Benefit',
                'sub_fields' => [
                    [
                        'key' => 'field_programs_private_benefit_text',
                        'label' => 'Benefit Text',
                        'name' => 'benefit_text',
                        'type' => 'text',
                        'instructions' => 'The benefit text.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Direct access to Joanna throughout engagement',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_private_cta_text',
                'label' => 'Private Training CTA Text',
                'name' => 'programs_private_cta_text',
                'type' => 'text',
                'instructions' => 'The text for the private training call-to-action button.',
                'required' => 0,
                'default_value' => 'Apply for Private Training →',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Speak & Rise Section
            [
                'key' => 'field_programs_speak_badge',
                'label' => 'Speak & Rise Badge Text',
                'name' => 'programs_speak_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the Speak & Rise heading.',
                'required' => 0,
                'default_value' => 'Group Training · Speak & Rise',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_speak_heading',
                'label' => 'Speak & Rise Heading',
                'name' => 'programs_speak_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the Speak & Rise section.',
                'required' => 0,
                'default_value' => 'Speak & Rise: Find Your Voice. Tell Your Story. Lead Your Room.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_speak_description_1',
                'label' => 'Speak & Rise Description 1',
                'name' => 'programs_speak_description_1',
                'type' => 'textarea',
                'instructions' => 'The first description paragraph for the Speak & Rise section.',
                'required' => 0,
                'default_value' => 'Speak & Rise is Joanna\'s group training experience — a powerful, community-driven program for leaders who are ready to develop their story, sharpen their message, and step into their voice alongside a group of peers doing the same brave work.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_speak_description_2',
                'label' => 'Speak & Rise Description 2',
                'name' => 'programs_speak_description_2',
                'type' => 'textarea',
                'instructions' => 'The second description paragraph for the Speak & Rise section.',
                'required' => 0,
                'default_value' => 'It is the most accessible entry point into True Influence Method™️ — and it is anything but ordinary.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_speak_included_heading',
                'label' => 'Speak & Rise Included Heading',
                'name' => 'programs_speak_included_heading',
                'type' => 'text',
                'instructions' => 'The heading text for the "What\'s Included" section.',
                'required' => 0,
                'default_value' => 'What\'s Included:',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_speak_included_items',
                'label' => 'Speak & Rise Included Items',
                'name' => 'programs_speak_included_items',
                'type' => 'repeater',
                'instructions' => 'Add the items included in the Speak & Rise program.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Item',
                'sub_fields' => [
                    [
                        'key' => 'field_programs_speak_included_item_text',
                        'label' => 'Item Text',
                        'name' => 'item_text',
                        'type' => 'text',
                        'instructions' => 'The item text.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Live group training sessions with Joanna',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_speak_investment_label',
                'label' => 'Speak & Rise Investment Label',
                'name' => 'programs_speak_investment_label',
                'type' => 'text',
                'instructions' => 'The label for the investment section.',
                'required' => 0,
                'default_value' => 'Investment:',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_speak_investment_price',
                'label' => 'Speak & Rise Investment Price',
                'name' => 'programs_speak_investment_price',
                'type' => 'text',
                'instructions' => 'The investment price.',
                'required' => 0,
                'default_value' => 'From $6,000',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_speak_investment_note',
                'label' => 'Speak & Rise Investment Note',
                'name' => 'programs_speak_investment_note',
                'type' => 'text',
                'instructions' => 'The note below the investment price.',
                'required' => 0,
                'default_value' => '90-Day Mastermind & Retreat',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_speak_cta_text',
                'label' => 'Speak & Rise CTA Text',
                'name' => 'programs_speak_cta_text',
                'type' => 'text',
                'instructions' => 'The text for the Speak & Rise call-to-action button.',
                'required' => 0,
                'default_value' => 'Join Speak & Rise →',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Corporate Programs Section
            [
                'key' => 'field_programs_corporate_badge',
                'label' => 'Corporate Programs Badge Text',
                'name' => 'programs_corporate_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the corporate programs heading.',
                'required' => 0,
                'default_value' => 'Organizations & Teams',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_corporate_heading',
                'label' => 'Corporate Programs Heading',
                'name' => 'programs_corporate_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the corporate programs section.',
                'required' => 0,
                'default_value' => 'Corporate Programs: Bring True Influence to Your Organization.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_corporate_description_1',
                'label' => 'Corporate Programs Description 1',
                'name' => 'programs_corporate_description_1',
                'type' => 'textarea',
                'instructions' => 'The first description paragraph for the corporate programs section.',
                'required' => 0,
                'default_value' => 'Joanna works with leadership teams, executive groups, and organizations who want to build a culture of courageous, clear, and authentic communication. Every corporate engagement is fully customized — designed around your team\'s specific context, goals, and communication challenges.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_corporate_description_2',
                'label' => 'Corporate Programs Description 2',
                'name' => 'programs_corporate_description_2',
                'type' => 'textarea',
                'instructions' => 'The second description paragraph for the corporate programs section.',
                'required' => 0,
                'default_value' => 'Whether you are preparing leaders for high-stakes presentations, building a stronger executive voice across your organization, or embedding a communication methodology at scale — Joanna\'s corporate work delivers transformation that is immediately felt and lasting in impact.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_corporate_offerings_heading',
                'label' => 'Corporate Programs Offerings Heading',
                'name' => 'programs_corporate_offerings_heading',
                'type' => 'text',
                'instructions' => 'The heading text for the corporate offerings section.',
                'required' => 0,
                'default_value' => 'Corporate offerings include:',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_corporate_offerings',
                'label' => 'Corporate Programs Offerings',
                'name' => 'programs_corporate_offerings',
                'type' => 'repeater',
                'instructions' => 'Add the corporate program offerings.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Offering',
                'sub_fields' => [
                    [
                        'key' => 'field_programs_corporate_offering_text',
                        'label' => 'Offering Text',
                        'name' => 'offering_text',
                        'type' => 'text',
                        'instructions' => 'The offering text.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Custom leadership communication workshops and intensives',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_corporate_investment_label',
                'label' => 'Corporate Programs Investment Label',
                'name' => 'programs_corporate_investment_label',
                'type' => 'text',
                'instructions' => 'The label for the investment section.',
                'required' => 0,
                'default_value' => 'Investment:',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_corporate_investment_price',
                'label' => 'Corporate Programs Investment Price',
                'name' => 'programs_corporate_investment_price',
                'type' => 'text',
                'instructions' => 'The investment price.',
                'required' => 0,
                'default_value' => 'Custom Pricing',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_corporate_investment_note',
                'label' => 'Corporate Programs Investment Note',
                'name' => 'programs_corporate_investment_note',
                'type' => 'text',
                'instructions' => 'The note below the investment price.',
                'required' => 0,
                'default_value' => 'Based on scope and team size',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_corporate_cta_text',
                'label' => 'Corporate Programs CTA Text',
                'name' => 'programs_corporate_cta_text',
                'type' => 'text',
                'instructions' => 'The text for the corporate programs call-to-action button.',
                'required' => 0,
                'default_value' => 'Inquire for Your Organization →',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-programs.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [
            'the_content',
            'excerpt',
            'discussion',
            'comments',
            'featured_image',
        ],
        'active' => true,
        'description' => 'ACF fields for the Programs page template.',
    ]);
}
