<?php

/**
 * Programs Page ACF Field Group
 *
 * Registers ACF fields for the programs page template.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_programs_page',
        'title' => 'Programs Page',
        'fields' => [
            // Hero Section
            [
                'key' => 'field_programs_hero_badge',
                'label' => 'Hero Badge Text',
                'name' => 'programs_hero_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the hero heading.',
                'required' => 0,
                'default_value' => 'Programs',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_hero_heading',
                'label' => 'Hero Heading',
                'name' => 'programs_hero_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the hero section.',
                'required' => 0,
                'default_value' => 'Three Offers. One Method. Transformation at Every Level.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_hero_description',
                'label' => 'Hero Description',
                'name' => 'programs_hero_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the hero heading.',
                'required' => 0,
                'default_value' => 'Joanna offers three distinct paths into True Influence Method™️ — each designed for a different context, depth, and investment. All three are grounded in same rigorous process. All three create lasting change.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],

            // Three Paths Section
            [
                'key' => 'field_programs_paths_badge',
                'label' => 'Three Paths Badge Text',
                'name' => 'programs_paths_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the Three Paths heading.',
                'required' => 0,
                'default_value' => 'Three Paths',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_paths_heading',
                'label' => 'Three Paths Heading',
                'name' => 'programs_paths_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the Three Paths section.',
                'required' => 0,
                'default_value' => 'One Method. Three Paths. You Choose Your Level of Commitment.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_paths_description',
                'label' => 'Three Paths Description',
                'name' => 'programs_paths_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the Three Paths section.',
                'required' => 0,
                'default_value' => 'Transformation is priceless. But your investment needs to match the demand on your attention, energy, and focus — or you won\'t show up fully. That\'s the truth of why this works.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_paths',
                'label' => 'Three Paths',
                'name' => 'programs_paths',
                'type' => 'repeater',
                'instructions' => 'Add the three program paths (Mastermind, Cohort, Private Client).',
                'required' => 0,
                'collapsed' => 'field_programs_path_title',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Path',
                'sub_fields' => [
                    [
                        'key' => 'field_programs_path_label',
                        'label' => 'Path Label',
                        'name' => 'path_label',
                        'type' => 'text',
                        'instructions' => 'The path label (e.g., "Path 1", "Path 2", "Path 3").',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Path 1',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_programs_path_title',
                        'label' => 'Path Title',
                        'name' => 'path_title',
                        'type' => 'text',
                        'instructions' => 'The path title (e.g., "Mastermind", "Cohort", "Private Client").',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Mastermind',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_programs_path_subtitle',
                        'label' => 'Path Subtitle',
                        'name' => 'path_subtitle',
                        'type' => 'text',
                        'instructions' => 'The path subtitle (e.g., "Self-Study + Retreat").',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Self-Study + Retreat',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_programs_path_highlight',
                        'label' => 'Highlight as Premium',
                        'name' => 'path_highlight',
                        'type' => 'true_false',
                        'instructions' => 'Enable to visually highlight this path as the premium tier.',
                        'required' => 0,
                        'default_value' => 0,
                        'message' => 'Highlight this path',
                        'ui' => 1,
                        'ui_on_text' => 'Yes',
                        'ui_off_text' => 'No',
                        'wrapper' => [
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_programs_path_who_for',
                        'label' => 'Who It\'s For',
                        'name' => 'path_who_for',
                        'type' => 'text',
                        'instructions' => 'Description of who this path is for.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Leaders who are ready to begin at their own pace',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '100',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_programs_path_features',
                        'label' => 'What You Get (Features)',
                        'name' => 'path_features',
                        'type' => 'repeater',
                        'instructions' => 'Add the features/benefits included in this path.',
                        'required' => 0,
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => 'Add Feature',
                        'sub_fields' => [
                            [
                                'key' => 'field_programs_path_feature_text',
                                'label' => 'Feature Text',
                                'name' => 'feature_text',
                                'type' => 'text',
                                'instructions' => 'The feature text.',
                                'required' => 0,
                                'default_value' => '',
                                'placeholder' => 'e.g., 90-day self-guided training',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '100',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_programs_path_access',
                        'label' => 'Access Level',
                        'name' => 'path_access',
                        'type' => 'text',
                        'instructions' => 'The access level description (e.g., "Retreat only", "Monthly + retreat").',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Retreat only',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_programs_path_cta_text',
                        'label' => 'CTA Text',
                        'name' => 'path_cta_text',
                        'type' => 'text',
                        'instructions' => 'The call-to-action button text.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Join Now →',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '34',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_programs_path_cta_link',
                        'label' => 'CTA Link',
                        'name' => 'path_cta_link',
                        'type' => 'url',
                        'instructions' => 'The call-to-action button link URL.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., /apply/',
                        'wrapper' => [
                            'width' => '100',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],

            // Set My Price Section
            [
                'key' => 'field_programs_setmyprice_heading',
                'label' => 'Set My Price Heading',
                'name' => 'programs_setmyprice_heading',
                'type' => 'text',
                'instructions' => 'The heading text for the Set My Price App section.',
                'required' => 0,
                'default_value' => 'Not sure which path is right for you? Let\'s find out together.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_setmyprice_description',
                'label' => 'Set My Price Description',
                'name' => 'programs_setmyprice_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the Set My Price App section.',
                'required' => 0,
                'default_value' => 'Joanna\'s training is worth more than $1,000,000 for clients who are 10/10 committed. But the price isn\'t the filter — your commitment is.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_setmyprice_cta_text',
                'label' => 'Set My Price CTA Text',
                'name' => 'programs_setmyprice_cta_text',
                'type' => 'text',
                'instructions' => 'The text for the Set My Price call-to-action button.',
                'required' => 0,
                'default_value' => 'Find My Program + Set My Price →',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_programs_setmyprice_cta_link',
                'label' => 'Set My Price CTA Link',
                'name' => 'programs_setmyprice_cta_link',
                'type' => 'url',
                'instructions' => 'The URL for the Set My Price call-to-action button.',
                'required' => 0,
                'default_value' => '',
                'placeholder' => 'e.g., /apply/',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-programs.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [
            'the_content',
            'excerpt',
            'discussion',
            'comments',
            'featured_image',
        ],
        'active' => true,
        'description' => 'ACF fields for the Programs page template.',
    ]);
}
