<?php

/**
 * Retreat Page ACF Field Group
 *
 * Registers ACF fields for the retreat page template.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_retreat_page',
        'title' => 'Retreat Page',
        'fields' => [
            // Hero Section
            [
                'key' => 'field_retreat_hero_badge',
                'label' => 'Hero Badge Text',
                'name' => 'retreat_hero_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the hero heading.',
                'required' => 0,
                'default_value' => 'Immersive Experience',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_hero_heading',
                'label' => 'Hero Heading',
                'name' => 'retreat_hero_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the hero section.',
                'required' => 0,
                'default_value' => 'True Influence Retreat',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_hero_description',
                'label' => 'Hero Description',
                'name' => 'retreat_hero_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the hero heading.',
                'required' => 0,
                'default_value' => 'A transformative 3-day experience where focused work, partner feedback, and live application converge to prepare you for the stage.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_hero_background_image',
                'label' => 'Hero Background Image',
                'name' => 'retreat_hero_background_image',
                'type' => 'image',
                'instructions' => 'The background image for the hero section.',
                'required' => 0,
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Overview Section
            [
                'key' => 'field_retreat_overview_badge',
                'label' => 'Overview Badge Text',
                'name' => 'retreat_overview_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the overview heading.',
                'required' => 0,
                'default_value' => 'Retreat Structure',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_overview_heading',
                'label' => 'Overview Heading',
                'name' => 'retreat_overview_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the overview section.',
                'required' => 0,
                'default_value' => 'All Levels, One Container',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_overview_description',
                'label' => 'Overview Description',
                'name' => 'retreat_overview_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the overview heading.',
                'required' => 0,
                'default_value' => 'This is a supportive working environment, not a passive experience.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_overview_badge_text',
                'label' => 'Overview Badge',
                'name' => 'retreat_overview_badge_text',
                'type' => 'text',
                'instructions' => 'The badge text displayed in the overview section.',
                'required' => 0,
                'default_value' => 'Everything leads to Stage Day',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_features',
                'label' => 'Retreat Features',
                'name' => 'retreat_features',
                'type' => 'repeater',
                'instructions' => 'Add the retreat features.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Feature',
                'sub_fields' => [
                    [
                        'key' => 'field_retreat_feature_title',
                        'label' => 'Feature Title',
                        'name' => 'feature_title',
                        'type' => 'text',
                        'instructions' => 'The feature title.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Focused Work',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_retreat_feature_description',
                        'label' => 'Feature Description',
                        'name' => 'feature_description',
                        'type' => 'textarea',
                        'instructions' => 'The feature description.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_retreat_feature_icon',
                        'label' => 'Feature Icon',
                        'name' => 'feature_icon',
                        'type' => 'select',
                        'instructions' => 'Select the icon for this feature.',
                        'required' => 0,
                        'choices' => [
                            'Target' => 'Target',
                            'Users' => 'Users',
                            'Play' => 'Play',
                            'BookOpen' => 'BookOpen',
                            'Crown' => 'Crown',
                            'Mic' => 'Mic',
                            'TrendingUp' => 'TrendingUp',
                            'Award' => 'Award',
                            'Home' => 'Home',
                            'Sparkles' => 'Sparkles',
                            'Calendar' => 'Calendar',
                            'Clock' => 'Clock',
                            'CheckCircle2' => 'CheckCircle2',
                            'Trophy' => 'Trophy',
                            'Zap' => 'Zap',
                            'ArrowRight' => 'ArrowRight',
                            'ChevronDown' => 'ChevronDown',
                        ],
                        'default_value' => 'Target',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Day Schedule Section
            [
                'key' => 'field_retreat_schedule_badge',
                'label' => 'Schedule Badge Text',
                'name' => 'retreat_schedule_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the schedule heading.',
                'required' => 0,
                'default_value' => 'The Journey',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_schedule_heading',
                'label' => 'Schedule Heading',
                'name' => 'retreat_schedule_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the schedule section.',
                'required' => 0,
                'default_value' => 'Three Days to Transformation',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_schedule_description',
                'label' => 'Schedule Description',
                'name' => 'retreat_schedule_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the schedule heading.',
                'required' => 0,
                'default_value' => 'From arrival to stage day, every moment is designed for growth',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_days',
                'label' => 'Retreat Days',
                'name' => 'retreat_days',
                'type' => 'repeater',
                'instructions' => 'Add the retreat days.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Day',
                'sub_fields' => [
                    [
                        'key' => 'field_retreat_day_number',
                        'label' => 'Day Number',
                        'name' => 'day_number',
                        'type' => 'number',
                        'instructions' => 'The day number (1, 2, 3, etc.).',
                        'required' => 0,
                        'default_value' => 1,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => 1,
                        'max' => '',
                        'step' => 1,
                        'wrapper' => [
                            'width' => '25',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_retreat_day_title',
                        'label' => 'Day Title',
                        'name' => 'day_title',
                        'type' => 'text',
                        'instructions' => 'The title for this day.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Arrival Day',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '75',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_retreat_day_theme',
                        'label' => 'Day Theme',
                        'name' => 'day_theme',
                        'type' => 'text',
                        'instructions' => 'The theme for this day.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Break the Performance',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_retreat_day_sessions',
                        'label' => 'Day Sessions',
                        'name' => 'day_sessions',
                        'type' => 'repeater',
                        'instructions' => 'Add the sessions for this day.',
                        'required' => 0,
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => 'Add Session',
                        'sub_fields' => [
                            [
                                'key' => 'field_retreat_session_period',
                                'label' => 'Session Period',
                                'name' => 'session_period',
                                'type' => 'text',
                                'instructions' => 'The period label (e.g., AM SESSION, PM SESSION).',
                                'required' => 0,
                                'default_value' => '',
                                'placeholder' => 'e.g., AM SESSION',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                            ],
                            [
                                'key' => 'field_retreat_session_time',
                                'label' => 'Session Time',
                                'name' => 'session_time',
                                'type' => 'text',
                                'instructions' => 'The time for this session (optional).',
                                'required' => 0,
                                'default_value' => '',
                                'placeholder' => 'e.g., After Dinner',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                            ],
                            [
                                'key' => 'field_retreat_session_activities',
                                'label' => 'Session Activities',
                                'name' => 'session_activities',
                                'type' => 'repeater',
                                'instructions' => 'Add the activities for this session.',
                                'required' => 0,
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'block',
                                'button_label' => 'Add Activity',
                                'sub_fields' => [
                                    [
                                        'key' => 'field_retreat_activity_time',
                                        'label' => 'Activity Time',
                                        'name' => 'activity_time',
                                        'type' => 'text',
                                        'instructions' => 'The time for this activity (optional).',
                                        'required' => 0,
                                        'default_value' => '',
                                        'placeholder' => 'e.g., 3:00 PM',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                    ],
                                    [
                                        'key' => 'field_retreat_activity_title',
                                        'label' => 'Activity Title',
                                        'name' => 'activity_title',
                                        'type' => 'text',
                                        'instructions' => 'The activity title.',
                                        'required' => 0,
                                        'default_value' => '',
                                        'placeholder' => 'e.g., Welcome + Container Setting',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                    ],
                                    [
                                        'key' => 'field_retreat_activity_description',
                                        'label' => 'Activity Description',
                                        'name' => 'activity_description',
                                        'type' => 'textarea',
                                        'instructions' => 'The activity description.',
                                        'required' => 0,
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => 3,
                                        'new_lines' => 'wpautop',
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                    ],
                                    [
                                        'key' => 'field_retreat_activity_highlight',
                                        'label' => 'Highlight Activity',
                                        'name' => 'activity_highlight',
                                        'type' => 'true_false',
                                        'instructions' => 'Check to highlight this activity.',
                                        'required' => 0,
                                        'default_value' => 0,
                                        'ui' => 1,
                                        'ui_on_text' => 'Yes',
                                        'ui_off_text' => 'No',
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                    ],
                                    [
                                        'key' => 'field_retreat_activity_special_note',
                                        'label' => 'Special Note',
                                        'name' => 'activity_special_note',
                                        'type' => 'text',
                                        'instructions' => 'A special note for this activity (optional).',
                                        'required' => 0,
                                        'default_value' => '',
                                        'placeholder' => 'e.g., Private clients exclusive',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                    ],
                                ],
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Experience Section
            [
                'key' => 'field_retreat_experience_badge',
                'label' => 'Experience Badge Text',
                'name' => 'retreat_experience_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the experience heading.',
                'required' => 0,
                'default_value' => 'The Experience',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_experience_heading',
                'label' => 'Experience Heading',
                'name' => 'retreat_experience_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the experience section.',
                'required' => 0,
                'default_value' => 'Not Just Training. Transformation.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_experience_description',
                'label' => 'Experience Description',
                'name' => 'retreat_experience_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the experience heading.',
                'required' => 0,
                'default_value' => 'This is a supportive working environment where every moment leads to growth',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_highlights',
                'label' => 'Retreat Highlights',
                'name' => 'retreat_highlights',
                'type' => 'repeater',
                'instructions' => 'Add the retreat highlights.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Highlight',
                'sub_fields' => [
                    [
                        'key' => 'field_retreat_highlight_title',
                        'label' => 'Highlight Title',
                        'name' => 'highlight_title',
                        'type' => 'text',
                        'instructions' => 'The highlight title.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Relaxation Room',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_retreat_highlight_description',
                        'label' => 'Highlight Description',
                        'name' => 'highlight_description',
                        'type' => 'textarea',
                        'instructions' => 'The highlight description.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_retreat_highlight_icon',
                        'label' => 'Highlight Icon',
                        'name' => 'highlight_icon',
                        'type' => 'select',
                        'instructions' => 'Select the icon for this highlight.',
                        'required' => 0,
                        'choices' => [
                            'Target' => 'Target',
                            'Users' => 'Users',
                            'Play' => 'Play',
                            'BookOpen' => 'BookOpen',
                            'Crown' => 'Crown',
                            'Mic' => 'Mic',
                            'TrendingUp' => 'TrendingUp',
                            'Award' => 'Award',
                            'Home' => 'Home',
                            'Sparkles' => 'Sparkles',
                            'Calendar' => 'Calendar',
                            'Clock' => 'Clock',
                            'CheckCircle2' => 'CheckCircle2',
                            'Trophy' => 'Trophy',
                            'Zap' => 'Zap',
                            'ArrowRight' => 'ArrowRight',
                            'ChevronDown' => 'ChevronDown',
                        ],
                        'default_value' => 'Zap',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_callout_title',
                'label' => 'Callout Title',
                'name' => 'retreat_callout_title',
                'type' => 'text',
                'instructions' => 'The title for the callout box.',
                'required' => 0,
                'default_value' => 'Every Activity Has Purpose',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_callout_description',
                'label' => 'Callout Description',
                'name' => 'retreat_callout_description',
                'type' => 'textarea',
                'instructions' => 'The description for the callout box.',
                'required' => 0,
                'default_value' => 'From focused work sessions to partner feedback, from pod integration to stage performance - every element is designed to build your confidence and prepare you for the spotlight.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Stages Section
            [
                'key' => 'field_retreat_stages_badge',
                'label' => 'Stages Badge Text',
                'name' => 'retreat_stages_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the stages heading.',
                'required' => 0,
                'default_value' => 'Stage Day',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_stages_heading',
                'label' => 'Stages Heading',
                'name' => 'retreat_stages_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the stages section.',
                'required' => 0,
                'default_value' => 'Be Seen and Celebrated',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_stages_description',
                'label' => 'Stages Description',
                'name' => 'retreat_stages_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the stages heading.',
                'required' => 0,
                'default_value' => 'The culmination of your journey - deliver your talk with real-time feedback and recognition',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_stage_experience_heading',
                'label' => 'Stage Experience Heading',
                'name' => 'retreat_stage_experience_heading',
                'type' => 'text',
                'instructions' => 'The heading for the stage experience box.',
                'required' => 0,
                'default_value' => 'The Stage Experience',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_stage_experience_items',
                'label' => 'Stage Experience Items',
                'name' => 'retreat_stage_experience_items',
                'type' => 'repeater',
                'instructions' => 'Add the stage experience items.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Item',
                'sub_fields' => [
                    [
                        'key' => 'field_retreat_stage_experience_item',
                        'label' => 'Item Text',
                        'name' => 'stage_experience_item',
                        'type' => 'text',
                        'instructions' => 'The item text.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Set intention & feedback framework',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_qualification_heading',
                'label' => 'Qualification Heading',
                'name' => 'retreat_qualification_heading',
                'type' => 'text',
                'instructions' => 'The heading for the qualification box.',
                'required' => 0,
                'default_value' => 'Qualification',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_qualification_description',
                'label' => 'Qualification Description',
                'name' => 'retreat_qualification_description',
                'type' => 'textarea',
                'instructions' => 'The description for the qualification box.',
                'required' => 0,
                'default_value' => 'Scores determine your advancement through the program, recognize top speakers, and identify promotions to the next level.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_qualification_items',
                'label' => 'Qualification Items',
                'name' => 'retreat_qualification_items',
                'type' => 'repeater',
                'instructions' => 'Add the qualification items.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Item',
                'sub_fields' => [
                    [
                        'key' => 'field_retreat_qualification_item_icon',
                        'label' => 'Item Icon',
                        'name' => 'qualification_item_icon',
                        'type' => 'select',
                        'instructions' => 'Select the icon for this item.',
                        'required' => 0,
                        'choices' => [
                            'Target' => 'Target',
                            'Users' => 'Users',
                            'Play' => 'Play',
                            'BookOpen' => 'BookOpen',
                            'Crown' => 'Crown',
                            'Mic' => 'Mic',
                            'TrendingUp' => 'TrendingUp',
                            'Award' => 'Award',
                            'Home' => 'Home',
                            'Sparkles' => 'Sparkles',
                            'Calendar' => 'Calendar',
                            'Clock' => 'Clock',
                            'CheckCircle2' => 'CheckCircle2',
                            'Trophy' => 'Trophy',
                            'Zap' => 'Zap',
                            'ArrowRight' => 'ArrowRight',
                            'ChevronDown' => 'ChevronDown',
                        ],
                        'default_value' => 'Trophy',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_retreat_qualification_item_label',
                        'label' => 'Item Label',
                        'name' => 'qualification_item_label',
                        'type' => 'text',
                        'instructions' => 'The item label.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Top Speakers',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_awards_badge',
                'label' => 'Awards Badge Text',
                'name' => 'retreat_awards_badge',
                'type' => 'text',
                'instructions' => 'The badge text for the awards section.',
                'required' => 0,
                'default_value' => 'Awards & Recognition',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_awards',
                'label' => 'Retreat Awards',
                'name' => 'retreat_awards',
                'type' => 'repeater',
                'instructions' => 'Add the retreat awards.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Award',
                'sub_fields' => [
                    [
                        'key' => 'field_retreat_award_title',
                        'label' => 'Award Title',
                        'name' => 'award_title',
                        'type' => 'text',
                        'instructions' => 'The award title.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Top 3 Appreciation Awards',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_retreat_award_description',
                        'label' => 'Award Description',
                        'name' => 'award_description',
                        'type' => 'textarea',
                        'instructions' => 'The award description.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // CTA Section
            [
                'key' => 'field_retreat_cta_badge',
                'label' => 'CTA Badge Text',
                'name' => 'retreat_cta_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the CTA heading.',
                'required' => 0,
                'default_value' => 'Your Next Step',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_cta_heading',
                'label' => 'CTA Heading',
                'name' => 'retreat_cta_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the CTA section.',
                'required' => 0,
                'default_value' => 'Ready to Transform?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_cta_description',
                'label' => 'CTA Description',
                'name' => 'retreat_cta_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the CTA heading.',
                'required' => 0,
                'default_value' => 'Join the True Influence Retreat and experience three days of focused work, partner feedback, and stage performance that will elevate your leadership presence.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_cta_button_text',
                'label' => 'CTA Button Text',
                'name' => 'retreat_cta_button_text',
                'type' => 'text',
                'instructions' => 'The text for the CTA button.',
                'required' => 0,
                'default_value' => 'Apply Now',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_cta_button_link',
                'label' => 'CTA Button Link',
                'name' => 'retreat_cta_button_link',
                'type' => 'url',
                'instructions' => 'The URL for the CTA button.',
                'required' => 0,
                'default_value' => '/#contact',
                'placeholder' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_retreat_quote',
                'label' => 'Quote',
                'name' => 'retreat_quote',
                'type' => 'textarea',
                'instructions' => 'The quote displayed at the bottom of the CTA section.',
                'required' => 0,
                'default_value' => '"This retreat isn\'t just about learning to speak - it\'s about discovering the power of your voice and learning to use it with impact."',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-retreat.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [
            'the_content',
            'excerpt',
            'discussion',
            'comments',
            'featured_image',
        ],
        'active' => true,
        'description' => 'ACF fields for the Retreat page template.',
    ]);
}
