<?php

/**
 * Social Proof Section ACF Field Group
 *
 * Registers ACF fields for the social proof section on the front page.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_social_proof_section',
        'title' => 'Social Proof Section',
        'fields' => [
            [
                'key' => 'field_social_proof_badge_text',
                'label' => 'Badge Text',
                'name' => 'social_proof_badge_text',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the testimonials.',
                'required' => 0,
                'default_value' => 'Trusted by Leaders',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_testimonials',
                'label' => 'Testimonials',
                'name' => 'testimonials',
                'type' => 'repeater',
                'instructions' => 'Add testimonials from clients.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 3,
                'layout' => 'block',
                'button_label' => 'Add Testimonial',
                'sub_fields' => [
                    [
                        'key' => 'field_testimonial_quote',
                        'label' => 'Quote',
                        'name' => 'testimonial_quote',
                        'type' => 'textarea',
                        'instructions' => 'The testimonial quote.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'Enter the testimonial quote...',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_testimonial_author',
                        'label' => 'Author',
                        'name' => 'testimonial_author',
                        'type' => 'text',
                        'instructions' => 'The author of the testimonial.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., A. Robinson',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_testimonial_type',
                        'label' => 'Type',
                        'name' => 'testimonial_type',
                        'type' => 'text',
                        'instructions' => 'The type of client (e.g., Private Client, Corporate Client).',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Private Client',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_testimonial_image',
                        'label' => 'Author Image',
                        'name' => 'testimonial_image',
                        'type' => 'image',
                        'instructions' => 'The image of the testimonial author.',
                        'required' => 0,
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Metric 1: Years of Impact
            [
                'key' => 'field_stats_years_number',
                'label' => 'Years of Impact - Number',
                'name' => 'stats_years_number',
                'type' => 'text',
                'instructions' => 'The number for "Years of Impact" stat (e.g., 30).',
                'required' => 0,
                'default_value' => '30',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_stats_years_suffix',
                'label' => 'Years of Impact - Suffix',
                'name' => 'stats_years_suffix',
                'type' => 'text',
                'instructions' => 'The suffix after the number (e.g., "+").',
                'required' => 0,
                'default_value' => '+',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_stats_years_label',
                'label' => 'Years of Impact - Label',
                'name' => 'stats_years_label',
                'type' => 'text',
                'instructions' => 'The label for "Years of Impact" stat.',
                'required' => 0,
                'default_value' => 'Years of Impact',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Metric 2: Leaders Transformed
            [
                'key' => 'field_stats_leaders_number',
                'label' => 'Leaders Transformed - Number',
                'name' => 'stats_leaders_number',
                'type' => 'text',
                'instructions' => 'The number for "Leaders Transformed" stat (e.g., 10000).',
                'required' => 0,
                'default_value' => '10000',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_stats_leaders_suffix',
                'label' => 'Leaders Transformed - Suffix',
                'name' => 'stats_leaders_suffix',
                'type' => 'text',
                'instructions' => 'The suffix after the number (e.g., "+").',
                'required' => 0,
                'default_value' => '+',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_stats_leaders_label',
                'label' => 'Leaders Transformed - Label',
                'name' => 'stats_leaders_label',
                'type' => 'text',
                'instructions' => 'The label for "Leaders Transformed" stat.',
                'required' => 0,
                'default_value' => 'Leaders Transformed',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Metric 3: Revenue Generated
            [
                'key' => 'field_stats_revenue_number',
                'label' => 'Revenue Generated - Number',
                'name' => 'stats_revenue_number',
                'type' => 'text',
                'instructions' => 'The number for "Revenue Generated" stat (e.g., 42).',
                'required' => 0,
                'default_value' => '42',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_stats_revenue_suffix',
                'label' => 'Revenue Generated - Suffix',
                'name' => 'stats_revenue_suffix',
                'type' => 'text',
                'instructions' => 'The suffix after the number (e.g., "M+").',
                'required' => 0,
                'default_value' => 'M+',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_stats_revenue_prefix',
                'label' => 'Revenue Generated - Prefix',
                'name' => 'stats_revenue_prefix',
                'type' => 'text',
                'instructions' => 'The prefix before the number (e.g., "$").',
                'required' => 0,
                'default_value' => '$',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_stats_revenue_label',
                'label' => 'Revenue Generated - Label',
                'name' => 'stats_revenue_label',
                'type' => 'text',
                'instructions' => 'The label for "Revenue Generated" stat.',
                'required' => 0,
                'default_value' => 'Revenue Generated',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Metric 4: Stages Appeared On
            [
                'key' => 'field_stats_stages_number',
                'label' => 'Stages Appeared On - Number',
                'name' => 'stats_stages_number',
                'type' => 'text',
                'instructions' => 'The number for "Stages Appeared On" stat (e.g., 1100).',
                'required' => 0,
                'default_value' => '1100',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_stats_stages_suffix',
                'label' => 'Stages Appeared On - Suffix',
                'name' => 'stats_stages_suffix',
                'type' => 'text',
                'instructions' => 'The suffix after the number (e.g., "+").',
                'required' => 0,
                'default_value' => '+',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_stats_stages_label',
                'label' => 'Stages Appeared On - Label',
                'name' => 'stats_stages_label',
                'type' => 'text',
                'instructions' => 'The label for "Stages Appeared On" stat.',
                'required' => 0,
                'default_value' => 'Stages Appeared On',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'front-page.php',
                ],
            ],
        ],
        'menu_order' => 3,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [],
        'active' => true,
        'description' => 'Configure the social proof section content for the front page.',
    ]);
}
