<?php

/**
 * Success Stories Page ACF Field Group
 *
 * Registers ACF fields for the success stories page template.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_success_stories_page',
        'title' => 'Success Stories Page',
        'fields' => [
            // Hero Section
            [
                'key' => 'field_success_stories_hero_badge',
                'label' => 'Hero Badge Text',
                'name' => 'success_stories_hero_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the hero heading.',
                'required' => 0,
                'default_value' => 'Client Transformations',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_success_stories_hero_heading',
                'label' => 'Hero Heading',
                'name' => 'success_stories_hero_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the hero section.',
                'required' => 0,
                'default_value' => 'What Happens When Leaders Own Their Story.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_success_stories_hero_description',
                'label' => 'Hero Description',
                'name' => 'success_stories_hero_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the hero heading.',
                'required' => 0,
                'default_value' => 'Joanna\'s clients are founders, CEOs, executives, and mission-driven leaders from around the world. What they share is this: they arrived with something real to say — and left knowing exactly how to say it.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_success_stories_hero_background_image',
                'label' => 'Hero Background Image',
                'name' => 'success_stories_hero_background_image',
                'type' => 'image',
                'instructions' => 'The background image for the hero section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Testimonials Section
            [
                'key' => 'field_success_stories_testimonials_heading',
                'label' => 'Testimonials Section Heading',
                'name' => 'success_stories_testimonials_heading',
                'type' => 'text',
                'instructions' => 'The heading text for the testimonials section.',
                'required' => 0,
                'default_value' => 'Voices of Transformation',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_success_stories_testimonials_description',
                'label' => 'Testimonials Section Description',
                'name' => 'success_stories_testimonials_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the testimonials section.',
                'required' => 0,
                'default_value' => 'Real stories from leaders who found their voice and transformed their impact.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 2,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_success_stories_testimonials',
                'label' => 'Testimonials',
                'name' => 'success_stories_testimonials',
                'type' => 'repeater',
                'instructions' => 'Add testimonials to display in the testimonials section.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Testimonial',
                'sub_fields' => [
                    [
                        'key' => 'field_success_stories_testimonial_quote',
                        'label' => 'Quote',
                        'name' => 'quote',
                        'type' => 'textarea',
                        'instructions' => 'The testimonial quote.',
                        'required' => 1,
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_success_stories_testimonial_author',
                        'label' => 'Author Name',
                        'name' => 'author',
                        'type' => 'text',
                        'instructions' => 'The name of the testimonial author.',
                        'required' => 1,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_success_stories_testimonial_type',
                        'label' => 'Author Type',
                        'name' => 'type',
                        'type' => 'text',
                        'instructions' => 'The type or role of the testimonial author (e.g., "CEO", "Executive Leader").',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_success_stories_testimonial_image',
                        'label' => 'Author Image',
                        'name' => 'image',
                        'type' => 'image',
                        'instructions' => 'The image of the testimonial author.',
                        'required' => 0,
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Case Studies Callout Section
            [
                'key' => 'field_success_stories_case_studies_badge',
                'label' => 'Case Studies Badge Text',
                'name' => 'success_stories_case_studies_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the case studies heading.',
                'required' => 0,
                'default_value' => 'Case Studies',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_success_stories_case_studies_heading',
                'label' => 'Case Studies Heading',
                'name' => 'success_stories_case_studies_heading',
                'type' => 'text',
                'instructions' => 'The heading text for the case studies section.',
                'required' => 0,
                'default_value' => 'See Full Transformations.',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_success_stories_case_studies_description',
                'label' => 'Case Studies Description',
                'name' => 'success_stories_case_studies_description',
                'type' => 'textarea',
                'instructions' => 'The description text for the case studies section.',
                'required' => 0,
                'default_value' => 'Joanna\'s client case studies go deeper — exploring specific challenge, process, and outcomes. If you\'d like to hear more about what is possible, reach out to Joanna\'s team and we\'ll share examples relevant to your situation.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_success_stories_case_studies_cta_text',
                'label' => 'Case Studies CTA Button Text',
                'name' => 'success_stories_case_studies_cta_text',
                'type' => 'text',
                'instructions' => 'The text for the call-to-action button.',
                'required' => 0,
                'default_value' => 'Request Client Examples',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_success_stories_case_studies_cta_link',
                'label' => 'Case Studies CTA Link',
                'name' => 'success_stories_case_studies_cta_link',
                'type' => 'page_link',
                'instructions' => 'Select the page for the call-to-action button.',
                'required' => 0,
                'post_type' => [],
                'taxonomy' => [],
                'allow_null' => 0,
                'multiple' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_success_stories_case_studies_background_image',
                'label' => 'Case Studies Background Image',
                'name' => 'success_stories_case_studies_background_image',
                'type' => 'image',
                'instructions' => 'The background image for the case studies section.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-success-stories.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [
            'the_content',
            'excerpt',
            'discussion',
            'comments',
            'revisions',
            'slug',
            'author',
            'format',
            'page_attributes',
            'featured_image',
            'categories',
            'tags',
            'send-trackbacks',
        ],
        'active' => true,
        'description' => 'Fields for the Success Stories page template.',
    ]);
}
