<?php

/**
 * Vault Page ACF Field Group
 *
 * Registers ACF fields for the vault page template.
 *
 * @package tim-wordpress
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group([
        'key' => 'group_vault_page',
        'title' => 'Vault Page',
        'fields' => [
            // Hero Section
            [
                'key' => 'field_vault_hero_badge',
                'label' => 'Hero Badge Text',
                'name' => 'vault_hero_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the hero heading.',
                'required' => 0,
                'default_value' => 'Complimentary Experience',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_hero_heading',
                'label' => 'Hero Heading',
                'name' => 'vault_hero_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the hero section.',
                'required' => 0,
                'default_value' => 'Enter The Vault',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_hero_description',
                'label' => 'Hero Description',
                'name' => 'vault_hero_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the hero heading.',
                'required' => 0,
                'default_value' => 'A free monthly safe space for women leaders to tell their story, connect with peers, and unlock your authentic voice.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_hero_background_image',
                'label' => 'Hero Background Image',
                'name' => 'vault_hero_background_image',
                'type' => 'image',
                'instructions' => 'The background image for the hero section.',
                'required' => 0,
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_hero_primary_cta_text',
                'label' => 'Hero Primary CTA Text',
                'name' => 'vault_hero_primary_cta_text',
                'type' => 'text',
                'instructions' => 'The text for the primary call-to-action button.',
                'required' => 0,
                'default_value' => 'Register Now',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_hero_primary_cta_link',
                'label' => 'Hero Primary CTA Link',
                'name' => 'vault_hero_primary_cta_link',
                'type' => 'page_link',
                'instructions' => 'Select the page for the primary call-to-action button.',
                'required' => 0,
                'post_type' => [
                    0 => 'page',
                ],
                'taxonomy' => [],
                'allow_null' => 0,
                'multiple' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_hero_time_info',
                'label' => 'Hero Time Info',
                'name' => 'vault_hero_time_info',
                'type' => 'text',
                'instructions' => 'The time information displayed below the CTA button.',
                'required' => 0,
                'default_value' => 'First Fridays at 12 PM MST',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // About Section
            [
                'key' => 'field_vault_about_badge',
                'label' => 'About Badge Text',
                'name' => 'vault_about_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the about heading.',
                'required' => 0,
                'default_value' => 'What is The Vault?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_about_heading',
                'label' => 'About Heading',
                'name' => 'vault_about_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the about section.',
                'required' => 0,
                'default_value' => 'A Safe Space for Your Voice',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_about_description',
                'label' => 'About Description',
                'name' => 'vault_about_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the about heading.',
                'required' => 0,
                'default_value' => 'The Vault is Joanna\'s gift to women leaders seeking a supportive community to share their story, practice their message, and connect with like-minded peers. This complimentary monthly gathering provides a judgment-free environment where you can speak authentically and receive gentle guidance.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_about_image',
                'label' => 'About Image',
                'name' => 'vault_about_image',
                'type' => 'image',
                'instructions' => 'The image for the about section.',
                'required' => 0,
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_about_features',
                'label' => 'About Features',
                'name' => 'vault_about_features',
                'type' => 'repeater',
                'instructions' => 'Add features for the about section.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Feature',
                'sub_fields' => [
                    [
                        'key' => 'field_vault_about_feature_title',
                        'label' => 'Feature Title',
                        'name' => 'vault_about_feature_title',
                        'type' => 'text',
                        'instructions' => 'The title of the feature.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Story Sharing',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_vault_about_feature_description',
                        'label' => 'Feature Description',
                        'name' => 'vault_about_feature_description',
                        'type' => 'textarea',
                        'instructions' => 'The description of the feature.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Tell your story in a safe, supportive environment without judgment or pressure.',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Benefits Section
            [
                'key' => 'field_vault_benefits_badge',
                'label' => 'Benefits Badge Text',
                'name' => 'vault_benefits_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the benefits heading.',
                'required' => 0,
                'default_value' => 'Why Join?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_benefits_heading',
                'label' => 'Benefits Heading',
                'name' => 'vault_benefits_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the benefits section.',
                'required' => 0,
                'default_value' => 'What You\'ll Experience',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_benefits_items',
                'label' => 'Benefits Items',
                'name' => 'vault_benefits_items',
                'type' => 'repeater',
                'instructions' => 'Add benefits for the benefits section.',
                'required' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Benefit',
                'sub_fields' => [
                    [
                        'key' => 'field_vault_benefit_icon',
                        'label' => 'Icon',
                        'name' => 'vault_benefit_icon',
                        'type' => 'select',
                        'instructions' => 'Select the icon for this benefit.',
                        'required' => 0,
                        'choices' => [
                            'shield' => 'Shield',
                            'message-circle' => 'Message Circle',
                            'users' => 'Users',
                            'heart' => 'Heart',
                            'clock' => 'Clock',
                            'calendar' => 'Calendar',
                        ],
                        'default_value' => 'shield',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_vault_benefit_title',
                        'label' => 'Benefit Title',
                        'name' => 'vault_benefit_title',
                        'type' => 'text',
                        'instructions' => 'The title of the benefit.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., Safe Environment',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_vault_benefit_description',
                        'label' => 'Benefit Description',
                        'name' => 'vault_benefit_description',
                        'type' => 'textarea',
                        'instructions' => 'The description of the benefit.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'e.g., A judgment-free space where vulnerability is celebrated and confidentiality is honored.',
                        'maxlength' => '',
                        'rows' => 3,
                        'new_lines' => 'wpautop',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // CTA Section
            [
                'key' => 'field_vault_cta_background_image',
                'label' => 'CTA Background Image',
                'name' => 'vault_cta_background_image',
                'type' => 'image',
                'instructions' => 'The background image for the CTA section.',
                'required' => 0,
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_cta_badge',
                'label' => 'CTA Badge Text',
                'name' => 'vault_cta_badge',
                'type' => 'text',
                'instructions' => 'The badge text displayed above the CTA heading.',
                'required' => 0,
                'default_value' => 'Complimentary',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_cta_heading',
                'label' => 'CTA Heading',
                'name' => 'vault_cta_heading',
                'type' => 'text',
                'instructions' => 'The main heading text for the CTA section.',
                'required' => 0,
                'default_value' => 'Ready to Enter The Vault?',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_cta_description',
                'label' => 'CTA Description',
                'name' => 'vault_cta_description',
                'type' => 'textarea',
                'instructions' => 'The description text displayed below the CTA heading.',
                'required' => 0,
                'default_value' => 'Join our next First Friday gathering and take the first step toward unlocking your authentic voice in a supportive community of women leaders.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => 'wpautop',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_cta_primary_cta_text',
                'label' => 'CTA Primary CTA Text',
                'name' => 'vault_cta_primary_cta_text',
                'type' => 'text',
                'instructions' => 'The text for the primary call-to-action button.',
                'required' => 0,
                'default_value' => 'Register Now',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_cta_primary_cta_link',
                'label' => 'CTA Primary CTA Link',
                'name' => 'vault_cta_primary_cta_link',
                'type' => 'page_link',
                'instructions' => 'Select the page for the primary call-to-action button.',
                'required' => 0,
                'post_type' => [
                    0 => 'page',
                ],
                'taxonomy' => [],
                'allow_null' => 0,
                'multiple' => 0,
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_cta_secondary_cta_text',
                'label' => 'CTA Secondary CTA Text',
                'name' => 'vault_cta_secondary_cta_text',
                'type' => 'text',
                'instructions' => 'The text for the secondary call-to-action link.',
                'required' => 0,
                'default_value' => 'Explore Other Offerings',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_cta_secondary_cta_link',
                'label' => 'CTA Secondary CTA Link',
                'name' => 'vault_cta_secondary_cta_link',
                'type' => 'page_link',
                'instructions' => 'Select the page for the secondary call-to-action link.',
                'required' => 0,
                'post_type' => [
                    0 => 'page',
                ],
                'taxonomy' => [],
                'allow_null' => 0,
                'multiple' => 0,
                'wrapper' => [
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ],
            ],
            [
                'key' => 'field_vault_cta_time_info',
                'label' => 'CTA Time Info',
                'name' => 'vault_cta_time_info',
                'type' => 'text',
                'instructions' => 'The time information displayed below the CTA buttons.',
                'required' => 0,
                'default_value' => 'First Fridays at 12 PM MST • Free for all women leaders',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-vault.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => [
            0 => 'the_content',
            1 => 'excerpt',
            2 => 'discussion',
            3 => 'comments',
            4 => 'revisions',
            5 => 'slug',
            6 => 'author',
            7 => 'format',
            8 => 'page_attributes',
            9 => 'featured_image',
            10 => 'categories',
            11 => 'tags',
            12 => 'send-trackbacks',
        ],
        'active' => true,
        'description' => 'ACF fields for the Vault page template.',
    ]);
}
